#!/usr/bin/env python2

"""Tool to retrieve a token for a TCL4 InterUSS Platform Data Node.


Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import argparse

import client_tools


if __name__ == "__main__":
  parser = argparse.ArgumentParser(
    description='Retrieve and print an access_token for accessing a TCL4 '
                'InterUSS Platform node. To cache this token, you may want to '
                'run:\n'
                'export ACCESS_TOKEN=`./get_token`')
  client_tools.add_auth_arguments(parser)

  options = parser.parse_args()

  token = client_tools.get_token(options.auth_key, options.auth_url)
  print(token)
