#!/usr/bin/env python2

"""Tool to qeury the state of a TCL4 InterUSS Platform Data Node.


Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import argparse
import json
import os

import client_tools
import reports


if __name__ == "__main__":
  parser = argparse.ArgumentParser(
    description='Report the status of TCL4 InterUSS Platform grid cell '
                'in human-readable format')
  client_tools.add_auth_arguments(parser)
  client_tools.add_node_arguments(parser)
  parser.add_argument(
    '-t',
    '--access_token',
    dest='access_token',
    default=os.environ.get('ACCESS_TOKEN', None),
    help='OAuth access_token to access the TCL4 InterUSS Platform node. '
         'Defaults to ACCESS_TOKEN environment variable if defined',
    metavar='ACCESS_TOKEN')

  options = parser.parse_args()

  if options.access_token:
    token = options.access_token
  else:
    token_manager = client_tools.TokenManager(
        options.auth_url, options.auth_key)
    token = token_manager.get_token(client_tools.INTERUSS_SCOPE)
  node_url = client_tools.make_node_url(options)
  json_string = client_tools.get_metadata(token, node_url)
  metadata = json.loads(json_string)
  reports.print_operators(metadata)
