@startuml
center header ASTM Strategic Coordination
title Nominal planning test with priority

participant "Test Driver" as TD
participant "First-mover USS" as USS1
participant "Second USS" as USS2
participant "DSS"

== TD injects via First-mover USS non-conflicting flight 1 ==

TD -> USS1: PUT /inject/flight\n{"state": "Accepted"}
TD <- USS1: 200 Ok - Operational Intent 1 created\n{"result": "Planned"}

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing Operational Intent 1
TD <- DSS: 200 Ok - returns Operational Intent Reference 1 with entityid1 managed by First-mover USS

TD -> USS1: GET /uss/v1/operational_intents/{entityid1}
TD <- USS1: 200 Ok - returns Operational Intent 1

...

== TD injects via Second USS a conflicting flight 2 in space and/or time with a higher priority ==

TD -> USS2: PUT /inject/flight\n{"state": "Accepted"}
TD <- USS2: 200 Ok - Operational Intent 2 created\n{"result": "Planned"}

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing Operational Intent 2
TD <- DSS: 200 Ok - returns Operational Intent Reference 2 with entityid2 managed by Second USS

TD -> USS2: GET /uss/v1/operational_intents/{entityid2}
TD <- USS2: 200 Ok - returns Operational Intent 2

...

== TD transitions flight in Second USS to Activated ==

TD -> USS2: PUT /inject/flight\n{"state": "Activated"}
TD <- USS2: 200 Ok\n{"result": "Planned"}

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing Operational Intent 2
TD <- DSS: 200 Ok - returns Operational Intent Reference 2 with entityid2 managed by Second USS

TD -> USS2: GET /uss/v1/operational_intents/{entityid2}
TD <- USS2: 200 Ok - returns Operational Intent 2

...

== TD attempts to transition flight in First-mover USS to Activated ==

TD -> USS1: PUT /inject/flight\n{"state": "Activated"}
TD <- USS1: 200 Ok - Flight update rejected\n{"result": "ConflictWithFlight"}

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing Operational Intent 1
TD <- DSS: 200 Ok or 404 Not found - Operational Intent Reference 1 is either unchanged or deleted

TD -> USS1: GET /uss/v1/operational_intents/{entityid1}
TD <- USS1: 200 Ok - Operational Intent 1 is unchanged (if not deleted in DSS)

@enduml
