openapi: 3.0.2
info:
  title: DSS Auxiliary API
  version: 1.1.0

components:
  schemas:
    VersionResponse:
      type: object
      required:
        - version
      properties:
        version:
          description: The version of the DSS.
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          description: Human-readable message indicating what error occurred and/or why.
          type: string

    PoolResponse:
      type: object
      properties:
        dar_id:
          description: >-
            Identifier of the DSS Airspace Representation shared by the pool of DSS instances to which this DSS instance belongs.
            Each DSS instance participating in the pool should indicate the same DAR ID as this ID describes the DAR shared by the pool.
          type: string
          default: ""

    DSSInstancesResponse:
      type: object
      properties:
        dss_instances:
          type: array
          items:
            $ref: '#/components/schemas/DSSInstance'
          default: []
    DSSInstance:
      type: object
      properties:
        id:
          description: Identity of this DSS instance participating in the pool (locality).
          type: string
        public_endpoint:
          description: Public endpoint of this DSS instance
          type: string
        most_recent_heartbeat:
          description: Most recent heartbeat registered for this DSS instance.
          anyOf:
          - $ref: '#/components/schemas/Heartbeat'
      required:
      - id
    Heartbeat:
      type: object
      properties:
        timestamp:
          description: Time at which heartbeat was registered.
          type: string
          format: date-time
          example: '1985-04-12T23:20:50.52Z'
        reporter:
          description: Identity (via access token `sub` claim) of client reporting the heartbeat, or omitted if no client reported the heartbeat.
          type: string
          example: 'uss1'
          default: ''
        source:
          description: Source/trigger of this heartbeat.
          type: string
          example: Startup
        index:
          description: Index of this heartbeat within the set of all heartbeats for this pool participant.
          type: integer
          format: int64
          minimum: 0
          example: 1
          default: 0
        next_heartbeat_expected_before:
          description: The time by which a new heartbeat should be registered for this DSS instance if the DSS instance operator's system is behaving correctly.
          type: string
          format: date-time
          example: '1985-04-12T23:45:00Z'
          default: ''
      required:
      - timestamp
      - source

    CAsResponse:
      type: object
      properties:
        CAs:
          description: A list of certificates, each in PEM format.
          type: array
          items:
            type: string

paths:
  /aux/v1/version:
    get:
      tags: [ dss ]
      operationId: getVersion
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
          description: The version of the DSS is successfully returned.
      summary: Queries the version of the DSS.
  /aux/v1/validate_oauth:
    get:
      tags: [ dss ]
      operationId: validateOauth
      parameters:
        - name: owner
          description: Validate the owner claim matches the provided owner.
          schema:
            type: string
          in: query
          required: true
      responses:
        '200':
          description: The provided token was validated.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bearer access token was not provided in Authorization header,
            token could not be decoded, or token was invalid.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: The access token was decoded successfully but did not include
            a scope appropriate to this endpoint.
      summary: Validate Oauth token against the DSS.
      security:
        - Auth:
            - dss.read.identification_service_areas
        - Auth:
            - dss.write.identification_service_areas

  /aux/v1/pool:
    get:
      summary: Queries the current information about the pool of DSS instances constituting the DSS Airspace Representation.
      operationId: getPool
      tags: [ dss ]
      security:
      - Auth:
        - interuss.pool_status.read
      responses:
        '200':
          description: The information is successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolResponse'
        '401':
          description: >-
            Bearer access token was not provided in Authorization header, token
            could not be decoded, or token was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: >-
            The access token was decoded successfully but did not include a
            scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: >-
            The server has not implemented this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /aux/v1/pool/dss_instances:
    get:
      summary: Queries the current information for DSS instances participating in the pool.
      operationId: getDSSInstances
      tags: [ dss ]
      security:
      - Auth:
        - interuss.pool_status.read
      responses:
        '200':
          description: The known DSS instances participating in the pool are successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DSSInstancesResponse'
        '401':
          description: >-
            Bearer access token was not provided in Authorization header, token
            could not be decoded, or token was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: >-
            The access token was decoded successfully but did not include a
            scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: >-
            The server has not implemented this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /aux/v1/pool/dss_instances/heartbeat:
    put:
      summary: Record a new heartbeat from the DSS instance
      operationId: putDSSInstancesHeartbeat
      tags: [ dss ]
      security:
      - Auth:
        - interuss.pool_status.heartbeat.write
      parameters:
      - name: source
        in: query
        required: true
        description: The source of the timestamp
        schema:
          type: string
      - name: timestamp
        in: query
        required: false
        description: Override the timestamp value of the heartbeat. If not set, will use the current time. RFC 3339 format.
        schema:
          type: string
          format: date-time
      - name: next_heartbeat_expected_before
        in: query
        required: false
        description: Set the time before the next heartbeat is expected. RFC 3339 format.
        schema:
          type: string
          format: date-time
      responses:
        '201':
          description: The heartbeat have been recorded. The known DSS instances participating in the pool are successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DSSInstancesResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: >-
            The request was not properly formed or the parameters are invalid
        '401':
          description: >-
            Bearer access token was not provided in Authorization header, token
            could not be decoded, or token was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: >-
            The access token was decoded successfully but did not include a
            scope appropriate to this endpoint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: >-
            The server has not implemented this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /aux/v1/configuration/accepted_ca_certs:
    get:
      summary: Current certificates of certificate authorities (CAs) that this DSS instance accepts as legitimate signers of node certificates for the pool of DSS instances constituting the DSS Airspace Representation.
      operationId: getAcceptedCAs
      tags: [ dss ]
      responses:
        '200':
          description: The information is successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAsResponse'
        '501':
          description: >-
            The server has not implemented this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /aux/v1/configuration/ca_certs:
    get:
      summary: Current certificates of certificate authorities (CAs) that signed the node certificates for this DSS instance. May return more that one certificate (e.g. for rotations).  Other DSS instances in the pool should accept node certificates signed by these CAs.
      operationId: getInstanceCAs
      tags: [ dss ]
      responses:
        '200':
          description: The information is successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CAsResponse'
        '501':
          description: >-
            The server has not implemented this operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
security:
  - Auth:
      - dss.read.identification_service_areas
      - dss.write.identification_service_areas
      - interuss.pool_status.read
      - interuss.pool_status.heartbeat.write
tags:
  - name: dss
    description: Endpoints exposed by the DSS server.
