// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/dssproto/dss.proto

package dssproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteIdentificationServiceAreaRequest struct {
	// UUIDv4 of the Identification Service Area.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIdentificationServiceAreaRequest) Reset() {
	*m = DeleteIdentificationServiceAreaRequest{}
}
func (m *DeleteIdentificationServiceAreaRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIdentificationServiceAreaRequest) ProtoMessage()    {}
func (*DeleteIdentificationServiceAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{0}
}

func (m *DeleteIdentificationServiceAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIdentificationServiceAreaRequest.Unmarshal(m, b)
}
func (m *DeleteIdentificationServiceAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIdentificationServiceAreaRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIdentificationServiceAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIdentificationServiceAreaRequest.Merge(m, src)
}
func (m *DeleteIdentificationServiceAreaRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIdentificationServiceAreaRequest.Size(m)
}
func (m *DeleteIdentificationServiceAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIdentificationServiceAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIdentificationServiceAreaRequest proto.InternalMessageInfo

func (m *DeleteIdentificationServiceAreaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteIdentificationServiceAreaRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Response for a request to delete an Identification Service Area.
type DeleteIdentificationServiceAreaResponse struct {
	ServiceArea *IdentificationServiceArea `protobuf:"bytes,1,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	// DSS subscribers that this client now has the obligation to notify of the Identification Service Area just deleted.  This client must call DELETE for each provided URL according to the `/uss/identification_service_areas` path API.
	Subscribers          []*SubscriberToNotify `protobuf:"bytes,2,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteIdentificationServiceAreaResponse) Reset() {
	*m = DeleteIdentificationServiceAreaResponse{}
}
func (m *DeleteIdentificationServiceAreaResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIdentificationServiceAreaResponse) ProtoMessage()    {}
func (*DeleteIdentificationServiceAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{1}
}

func (m *DeleteIdentificationServiceAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIdentificationServiceAreaResponse.Unmarshal(m, b)
}
func (m *DeleteIdentificationServiceAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIdentificationServiceAreaResponse.Marshal(b, m, deterministic)
}
func (m *DeleteIdentificationServiceAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIdentificationServiceAreaResponse.Merge(m, src)
}
func (m *DeleteIdentificationServiceAreaResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIdentificationServiceAreaResponse.Size(m)
}
func (m *DeleteIdentificationServiceAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIdentificationServiceAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIdentificationServiceAreaResponse proto.InternalMessageInfo

func (m *DeleteIdentificationServiceAreaResponse) GetServiceArea() *IdentificationServiceArea {
	if m != nil {
		return m.ServiceArea
	}
	return nil
}

func (m *DeleteIdentificationServiceAreaResponse) GetSubscribers() []*SubscriberToNotify {
	if m != nil {
		return m.Subscribers
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	// UUIDV4 of the subscription of interest.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionRequest) Reset()         { *m = DeleteSubscriptionRequest{} }
func (m *DeleteSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionRequest) ProtoMessage()    {}
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{2}
}

func (m *DeleteSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionRequest.Unmarshal(m, b)
}
func (m *DeleteSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionRequest.Merge(m, src)
}
func (m *DeleteSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionRequest.Size(m)
}
func (m *DeleteSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionRequest proto.InternalMessageInfo

func (m *DeleteSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteSubscriptionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Response for a successful request to delete an Subscription.
type DeleteSubscriptionResponse struct {
	Subscription         *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteSubscriptionResponse) Reset()         { *m = DeleteSubscriptionResponse{} }
func (m *DeleteSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionResponse) ProtoMessage()    {}
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{3}
}

func (m *DeleteSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionResponse.Unmarshal(m, b)
}
func (m *DeleteSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionResponse.Merge(m, src)
}
func (m *DeleteSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionResponse.Size(m)
}
func (m *DeleteSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionResponse proto.InternalMessageInfo

func (m *DeleteSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

// Data provided when an off-nominal condition was encountered.
type ErrorResponse struct {
	// Human-readable message indicating what error occurred and/or why.
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{4}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// An enclosed area on the earth.
// The bounding edges of this polygon shall be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude.
// The winding order shall be interpreted as the order which produces the smaller area.
// The path between two vertices shall be the shortest possible path between those vertices.
// Edges may not cross.
// Vertices may not be duplicated.  In particular, the final polygon vertex shall not be identical to the first vertex.
type GeoPolygon struct {
	Vertices             []*LatLngPoint `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GeoPolygon) Reset()         { *m = GeoPolygon{} }
func (m *GeoPolygon) String() string { return proto.CompactTextString(m) }
func (*GeoPolygon) ProtoMessage()    {}
func (*GeoPolygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{5}
}

func (m *GeoPolygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoPolygon.Unmarshal(m, b)
}
func (m *GeoPolygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoPolygon.Marshal(b, m, deterministic)
}
func (m *GeoPolygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoPolygon.Merge(m, src)
}
func (m *GeoPolygon) XXX_Size() int {
	return xxx_messageInfo_GeoPolygon.Size(m)
}
func (m *GeoPolygon) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoPolygon.DiscardUnknown(m)
}

var xxx_messageInfo_GeoPolygon proto.InternalMessageInfo

func (m *GeoPolygon) GetVertices() []*LatLngPoint {
	if m != nil {
		return m.Vertices
	}
	return nil
}

type GetIdentificationServiceAreaRequest struct {
	// UUIDv4 of the Identification Service Area.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdentificationServiceAreaRequest) Reset()         { *m = GetIdentificationServiceAreaRequest{} }
func (m *GetIdentificationServiceAreaRequest) String() string { return proto.CompactTextString(m) }
func (*GetIdentificationServiceAreaRequest) ProtoMessage()    {}
func (*GetIdentificationServiceAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{6}
}

func (m *GetIdentificationServiceAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentificationServiceAreaRequest.Unmarshal(m, b)
}
func (m *GetIdentificationServiceAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentificationServiceAreaRequest.Marshal(b, m, deterministic)
}
func (m *GetIdentificationServiceAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentificationServiceAreaRequest.Merge(m, src)
}
func (m *GetIdentificationServiceAreaRequest) XXX_Size() int {
	return xxx_messageInfo_GetIdentificationServiceAreaRequest.Size(m)
}
func (m *GetIdentificationServiceAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentificationServiceAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentificationServiceAreaRequest proto.InternalMessageInfo

func (m *GetIdentificationServiceAreaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response to DSS request for the identification service area with the given id.
type GetIdentificationServiceAreaResponse struct {
	IdentificationServiceArea *IdentificationServiceArea `protobuf:"bytes,1,opt,name=identification_service_area,json=identificationServiceArea,proto3" json:"identification_service_area,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *GetIdentificationServiceAreaResponse) Reset()         { *m = GetIdentificationServiceAreaResponse{} }
func (m *GetIdentificationServiceAreaResponse) String() string { return proto.CompactTextString(m) }
func (*GetIdentificationServiceAreaResponse) ProtoMessage()    {}
func (*GetIdentificationServiceAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{7}
}

func (m *GetIdentificationServiceAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdentificationServiceAreaResponse.Unmarshal(m, b)
}
func (m *GetIdentificationServiceAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdentificationServiceAreaResponse.Marshal(b, m, deterministic)
}
func (m *GetIdentificationServiceAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdentificationServiceAreaResponse.Merge(m, src)
}
func (m *GetIdentificationServiceAreaResponse) XXX_Size() int {
	return xxx_messageInfo_GetIdentificationServiceAreaResponse.Size(m)
}
func (m *GetIdentificationServiceAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdentificationServiceAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdentificationServiceAreaResponse proto.InternalMessageInfo

func (m *GetIdentificationServiceAreaResponse) GetIdentificationServiceArea() *IdentificationServiceArea {
	if m != nil {
		return m.IdentificationServiceArea
	}
	return nil
}

type GetSubscriptionRequest struct {
	// UUIDv4 of the Identification Service Area.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionRequest) Reset()         { *m = GetSubscriptionRequest{} }
func (m *GetSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionRequest) ProtoMessage()    {}
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{8}
}

func (m *GetSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionRequest.Unmarshal(m, b)
}
func (m *GetSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionRequest.Merge(m, src)
}
func (m *GetSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionRequest.Size(m)
}
func (m *GetSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionRequest proto.InternalMessageInfo

func (m *GetSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response to DSS request for the subscription with the given id.
type GetSubscriptionResponse struct {
	Subscription         *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSubscriptionResponse) Reset()         { *m = GetSubscriptionResponse{} }
func (m *GetSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionResponse) ProtoMessage()    {}
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{9}
}

func (m *GetSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionResponse.Unmarshal(m, b)
}
func (m *GetSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionResponse.Merge(m, src)
}
func (m *GetSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionResponse.Size(m)
}
func (m *GetSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionResponse proto.InternalMessageInfo

func (m *GetSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

// An Identification Service Area (area in which remote ID services are being provided).  The DSS reports only these declarations and clients must exchange flight information peer-to-peer.
type IdentificationServiceArea struct {
	FlightsUrl string `protobuf:"bytes,1,opt,name=flights_url,json=flightsUrl,proto3" json:"flights_url,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner, and only requiring EntitySignatures for unowned Entities.
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// End time of service.  RFC 3339 format, per OpenAPI specification.
	TimeEnd *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// Beginning time of service.  RFC 3339 format, per OpenAPI specification.
	TimeStart            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	Version              string               `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IdentificationServiceArea) Reset()         { *m = IdentificationServiceArea{} }
func (m *IdentificationServiceArea) String() string { return proto.CompactTextString(m) }
func (*IdentificationServiceArea) ProtoMessage()    {}
func (*IdentificationServiceArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{10}
}

func (m *IdentificationServiceArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentificationServiceArea.Unmarshal(m, b)
}
func (m *IdentificationServiceArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentificationServiceArea.Marshal(b, m, deterministic)
}
func (m *IdentificationServiceArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentificationServiceArea.Merge(m, src)
}
func (m *IdentificationServiceArea) XXX_Size() int {
	return xxx_messageInfo_IdentificationServiceArea.Size(m)
}
func (m *IdentificationServiceArea) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentificationServiceArea.DiscardUnknown(m)
}

var xxx_messageInfo_IdentificationServiceArea proto.InternalMessageInfo

func (m *IdentificationServiceArea) GetFlightsUrl() string {
	if m != nil {
		return m.FlightsUrl
	}
	return ""
}

func (m *IdentificationServiceArea) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IdentificationServiceArea) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *IdentificationServiceArea) GetTimeEnd() *timestamp.Timestamp {
	if m != nil {
		return m.TimeEnd
	}
	return nil
}

func (m *IdentificationServiceArea) GetTimeStart() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStart
	}
	return nil
}

func (m *IdentificationServiceArea) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Point on the earth's surface.
type LatLngPoint struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLngPoint) Reset()         { *m = LatLngPoint{} }
func (m *LatLngPoint) String() string { return proto.CompactTextString(m) }
func (*LatLngPoint) ProtoMessage()    {}
func (*LatLngPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{11}
}

func (m *LatLngPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLngPoint.Unmarshal(m, b)
}
func (m *LatLngPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLngPoint.Marshal(b, m, deterministic)
}
func (m *LatLngPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLngPoint.Merge(m, src)
}
func (m *LatLngPoint) XXX_Size() int {
	return xxx_messageInfo_LatLngPoint.Size(m)
}
func (m *LatLngPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLngPoint.DiscardUnknown(m)
}

var xxx_messageInfo_LatLngPoint proto.InternalMessageInfo

func (m *LatLngPoint) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLngPoint) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

// Parameters for a request to create or update a reference to an Identification Service Area in the DSS.
type PutIdentificationServiceAreaParameters struct {
	Extents              *Volume4D `protobuf:"bytes,1,opt,name=extents,proto3" json:"extents,omitempty"`
	FlightsUrl           string    `protobuf:"bytes,2,opt,name=flights_url,json=flightsUrl,proto3" json:"flights_url,omitempty"`
	Version              string    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutIdentificationServiceAreaParameters) Reset() {
	*m = PutIdentificationServiceAreaParameters{}
}
func (m *PutIdentificationServiceAreaParameters) String() string { return proto.CompactTextString(m) }
func (*PutIdentificationServiceAreaParameters) ProtoMessage()    {}
func (*PutIdentificationServiceAreaParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{12}
}

func (m *PutIdentificationServiceAreaParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIdentificationServiceAreaParameters.Unmarshal(m, b)
}
func (m *PutIdentificationServiceAreaParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIdentificationServiceAreaParameters.Marshal(b, m, deterministic)
}
func (m *PutIdentificationServiceAreaParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIdentificationServiceAreaParameters.Merge(m, src)
}
func (m *PutIdentificationServiceAreaParameters) XXX_Size() int {
	return xxx_messageInfo_PutIdentificationServiceAreaParameters.Size(m)
}
func (m *PutIdentificationServiceAreaParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIdentificationServiceAreaParameters.DiscardUnknown(m)
}

var xxx_messageInfo_PutIdentificationServiceAreaParameters proto.InternalMessageInfo

func (m *PutIdentificationServiceAreaParameters) GetExtents() *Volume4D {
	if m != nil {
		return m.Extents
	}
	return nil
}

func (m *PutIdentificationServiceAreaParameters) GetFlightsUrl() string {
	if m != nil {
		return m.FlightsUrl
	}
	return ""
}

func (m *PutIdentificationServiceAreaParameters) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PutIdentificationServiceAreaRequest struct {
	// UUIDv4 of the Identification Service Area.
	Id                   string                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Params               *PutIdentificationServiceAreaParameters `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *PutIdentificationServiceAreaRequest) Reset()         { *m = PutIdentificationServiceAreaRequest{} }
func (m *PutIdentificationServiceAreaRequest) String() string { return proto.CompactTextString(m) }
func (*PutIdentificationServiceAreaRequest) ProtoMessage()    {}
func (*PutIdentificationServiceAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{13}
}

func (m *PutIdentificationServiceAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIdentificationServiceAreaRequest.Unmarshal(m, b)
}
func (m *PutIdentificationServiceAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIdentificationServiceAreaRequest.Marshal(b, m, deterministic)
}
func (m *PutIdentificationServiceAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIdentificationServiceAreaRequest.Merge(m, src)
}
func (m *PutIdentificationServiceAreaRequest) XXX_Size() int {
	return xxx_messageInfo_PutIdentificationServiceAreaRequest.Size(m)
}
func (m *PutIdentificationServiceAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIdentificationServiceAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutIdentificationServiceAreaRequest proto.InternalMessageInfo

func (m *PutIdentificationServiceAreaRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutIdentificationServiceAreaRequest) GetParams() *PutIdentificationServiceAreaParameters {
	if m != nil {
		return m.Params
	}
	return nil
}

// Response to a request to create or update a reference to an Identification Service Area in the DSS.
type PutIdentificationServiceAreaResponse struct {
	ServiceArea *IdentificationServiceArea `protobuf:"bytes,1,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	// DSS subscribers that this client now has the obligation to notify of the Identification Service Area changes just made.  This client must call PUT for each provided URL according to the `/uss/identification_service_areas/{id}` path API.
	Subscribers          []*SubscriberToNotify `protobuf:"bytes,2,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutIdentificationServiceAreaResponse) Reset()         { *m = PutIdentificationServiceAreaResponse{} }
func (m *PutIdentificationServiceAreaResponse) String() string { return proto.CompactTextString(m) }
func (*PutIdentificationServiceAreaResponse) ProtoMessage()    {}
func (*PutIdentificationServiceAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{14}
}

func (m *PutIdentificationServiceAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIdentificationServiceAreaResponse.Unmarshal(m, b)
}
func (m *PutIdentificationServiceAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIdentificationServiceAreaResponse.Marshal(b, m, deterministic)
}
func (m *PutIdentificationServiceAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIdentificationServiceAreaResponse.Merge(m, src)
}
func (m *PutIdentificationServiceAreaResponse) XXX_Size() int {
	return xxx_messageInfo_PutIdentificationServiceAreaResponse.Size(m)
}
func (m *PutIdentificationServiceAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIdentificationServiceAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutIdentificationServiceAreaResponse proto.InternalMessageInfo

func (m *PutIdentificationServiceAreaResponse) GetServiceArea() *IdentificationServiceArea {
	if m != nil {
		return m.ServiceArea
	}
	return nil
}

func (m *PutIdentificationServiceAreaResponse) GetSubscribers() []*SubscriberToNotify {
	if m != nil {
		return m.Subscribers
	}
	return nil
}

// Parameters for a request to create or update a subscription in the DSS.
type PutSubscriptionParameters struct {
	Callbacks            *SubscriptionCallbacks `protobuf:"bytes,1,opt,name=callbacks,proto3" json:"callbacks,omitempty"`
	Extents              *Volume4D              `protobuf:"bytes,2,opt,name=extents,proto3" json:"extents,omitempty"`
	Version              string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PutSubscriptionParameters) Reset()         { *m = PutSubscriptionParameters{} }
func (m *PutSubscriptionParameters) String() string { return proto.CompactTextString(m) }
func (*PutSubscriptionParameters) ProtoMessage()    {}
func (*PutSubscriptionParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{15}
}

func (m *PutSubscriptionParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSubscriptionParameters.Unmarshal(m, b)
}
func (m *PutSubscriptionParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSubscriptionParameters.Marshal(b, m, deterministic)
}
func (m *PutSubscriptionParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSubscriptionParameters.Merge(m, src)
}
func (m *PutSubscriptionParameters) XXX_Size() int {
	return xxx_messageInfo_PutSubscriptionParameters.Size(m)
}
func (m *PutSubscriptionParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSubscriptionParameters.DiscardUnknown(m)
}

var xxx_messageInfo_PutSubscriptionParameters proto.InternalMessageInfo

func (m *PutSubscriptionParameters) GetCallbacks() *SubscriptionCallbacks {
	if m != nil {
		return m.Callbacks
	}
	return nil
}

func (m *PutSubscriptionParameters) GetExtents() *Volume4D {
	if m != nil {
		return m.Extents
	}
	return nil
}

func (m *PutSubscriptionParameters) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PutSubscriptionRequest struct {
	// UUIDV4 of the subscription of interest.  Must be created by client before `PUT` call to create AreaSubscription in DSS because the client may receive a notification at that subscription before receiving a response from the DSS.
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Params               *PutSubscriptionParameters `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PutSubscriptionRequest) Reset()         { *m = PutSubscriptionRequest{} }
func (m *PutSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*PutSubscriptionRequest) ProtoMessage()    {}
func (*PutSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{16}
}

func (m *PutSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSubscriptionRequest.Unmarshal(m, b)
}
func (m *PutSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *PutSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSubscriptionRequest.Merge(m, src)
}
func (m *PutSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_PutSubscriptionRequest.Size(m)
}
func (m *PutSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutSubscriptionRequest proto.InternalMessageInfo

func (m *PutSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutSubscriptionRequest) GetParams() *PutSubscriptionParameters {
	if m != nil {
		return m.Params
	}
	return nil
}

// Response for a request to create or update a subscription.
type PutSubscriptionResponse struct {
	// Identification Service Areas in or near the subscription area at the time of creation/update, if `identification_service_area_url` callback was specified.
	ServiceAreas         []*IdentificationServiceArea `protobuf:"bytes,1,rep,name=service_areas,json=serviceAreas,proto3" json:"service_areas,omitempty"`
	Subscription         *Subscription                `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PutSubscriptionResponse) Reset()         { *m = PutSubscriptionResponse{} }
func (m *PutSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*PutSubscriptionResponse) ProtoMessage()    {}
func (*PutSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{17}
}

func (m *PutSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSubscriptionResponse.Unmarshal(m, b)
}
func (m *PutSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *PutSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSubscriptionResponse.Merge(m, src)
}
func (m *PutSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_PutSubscriptionResponse.Size(m)
}
func (m *PutSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutSubscriptionResponse proto.InternalMessageInfo

func (m *PutSubscriptionResponse) GetServiceAreas() []*IdentificationServiceArea {
	if m != nil {
		return m.ServiceAreas
	}
	return nil
}

func (m *PutSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

type SearchIdentificationServiceAreasRequest struct {
	// The area in which to search for Identification Service Areas.  Some Identification Service Areas near this area but wholly outside it may also be returned.
	Area string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	// If specified, indicates non-interest in any Identification Service Areas that end before this time.  RFC 3339 format, per OpenAPI specification.
	EarliestTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=earliest_time,json=earliestTime,proto3" json:"earliest_time,omitempty"`
	// If specified, indicates non-interest in any Identification Service Areas that start after this time.  RFC 3339 format, per OpenAPI specification.
	LatestTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"`
	// If specified, indicates non-interest in Identification Service Areas entirely above this altitude in meters above the WGS84 ellipsoid.
	MaxAltitude float64 `protobuf:"fixed64,4,opt,name=max_altitude,json=maxAltitude,proto3" json:"max_altitude,omitempty"`
	// If specified, indicates non-interest in Identification Service Areas entirely below this altitude in meters above the WGS84 ellipsoid.
	MinAltitude          float64  `protobuf:"fixed64,5,opt,name=min_altitude,json=minAltitude,proto3" json:"min_altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchIdentificationServiceAreasRequest) Reset() {
	*m = SearchIdentificationServiceAreasRequest{}
}
func (m *SearchIdentificationServiceAreasRequest) String() string { return proto.CompactTextString(m) }
func (*SearchIdentificationServiceAreasRequest) ProtoMessage()    {}
func (*SearchIdentificationServiceAreasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{18}
}

func (m *SearchIdentificationServiceAreasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchIdentificationServiceAreasRequest.Unmarshal(m, b)
}
func (m *SearchIdentificationServiceAreasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchIdentificationServiceAreasRequest.Marshal(b, m, deterministic)
}
func (m *SearchIdentificationServiceAreasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchIdentificationServiceAreasRequest.Merge(m, src)
}
func (m *SearchIdentificationServiceAreasRequest) XXX_Size() int {
	return xxx_messageInfo_SearchIdentificationServiceAreasRequest.Size(m)
}
func (m *SearchIdentificationServiceAreasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchIdentificationServiceAreasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchIdentificationServiceAreasRequest proto.InternalMessageInfo

func (m *SearchIdentificationServiceAreasRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *SearchIdentificationServiceAreasRequest) GetEarliestTime() *timestamp.Timestamp {
	if m != nil {
		return m.EarliestTime
	}
	return nil
}

func (m *SearchIdentificationServiceAreasRequest) GetLatestTime() *timestamp.Timestamp {
	if m != nil {
		return m.LatestTime
	}
	return nil
}

func (m *SearchIdentificationServiceAreasRequest) GetMaxAltitude() float64 {
	if m != nil {
		return m.MaxAltitude
	}
	return 0
}

func (m *SearchIdentificationServiceAreasRequest) GetMinAltitude() float64 {
	if m != nil {
		return m.MinAltitude
	}
	return 0
}

// Response to DSS query for Identification Service Areas in an area of interest.
type SearchIdentificationServiceAreasResponse struct {
	// Identification Service Areas in the area of interest.
	ServiceAreas         []*IdentificationServiceArea `protobuf:"bytes,1,rep,name=service_areas,json=serviceAreas,proto3" json:"service_areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SearchIdentificationServiceAreasResponse) Reset() {
	*m = SearchIdentificationServiceAreasResponse{}
}
func (m *SearchIdentificationServiceAreasResponse) String() string { return proto.CompactTextString(m) }
func (*SearchIdentificationServiceAreasResponse) ProtoMessage()    {}
func (*SearchIdentificationServiceAreasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{19}
}

func (m *SearchIdentificationServiceAreasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchIdentificationServiceAreasResponse.Unmarshal(m, b)
}
func (m *SearchIdentificationServiceAreasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchIdentificationServiceAreasResponse.Marshal(b, m, deterministic)
}
func (m *SearchIdentificationServiceAreasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchIdentificationServiceAreasResponse.Merge(m, src)
}
func (m *SearchIdentificationServiceAreasResponse) XXX_Size() int {
	return xxx_messageInfo_SearchIdentificationServiceAreasResponse.Size(m)
}
func (m *SearchIdentificationServiceAreasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchIdentificationServiceAreasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchIdentificationServiceAreasResponse proto.InternalMessageInfo

func (m *SearchIdentificationServiceAreasResponse) GetServiceAreas() []*IdentificationServiceArea {
	if m != nil {
		return m.ServiceAreas
	}
	return nil
}

type SearchSubscriptionsRequest struct {
	// The area in which to search for Subscriptions.  Some Subscriptions near this area but wholly outside it may also be returned.
	Area                 string   `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSubscriptionsRequest) Reset()         { *m = SearchSubscriptionsRequest{} }
func (m *SearchSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSubscriptionsRequest) ProtoMessage()    {}
func (*SearchSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{20}
}

func (m *SearchSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSubscriptionsRequest.Unmarshal(m, b)
}
func (m *SearchSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *SearchSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSubscriptionsRequest.Merge(m, src)
}
func (m *SearchSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSubscriptionsRequest.Size(m)
}
func (m *SearchSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSubscriptionsRequest proto.InternalMessageInfo

func (m *SearchSubscriptionsRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

// Response to DSS query for subscriptions in a particular area.
type SearchSubscriptionsResponse struct {
	// Subscriptions that overlap the specified area.
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchSubscriptionsResponse) Reset()         { *m = SearchSubscriptionsResponse{} }
func (m *SearchSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchSubscriptionsResponse) ProtoMessage()    {}
func (*SearchSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{21}
}

func (m *SearchSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSubscriptionsResponse.Unmarshal(m, b)
}
func (m *SearchSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *SearchSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSubscriptionsResponse.Merge(m, src)
}
func (m *SearchSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchSubscriptionsResponse.Size(m)
}
func (m *SearchSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSubscriptionsResponse proto.InternalMessageInfo

func (m *SearchSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

// Subscriber to notify of a creation/change/deletion of a change in the airspace.  This is provided by the DSS to a client changing the airspace, and it is the responsibility of the client changing the airspace (they will receive a set of these notification requests) to send a notification to each specified `url`.
type SubscriberToNotify struct {
	// Subscription(s) prompting this notification.
	Subscriptions        []*SubscriptionState `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Url                  string               `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubscriberToNotify) Reset()         { *m = SubscriberToNotify{} }
func (m *SubscriberToNotify) String() string { return proto.CompactTextString(m) }
func (*SubscriberToNotify) ProtoMessage()    {}
func (*SubscriberToNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{22}
}

func (m *SubscriberToNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriberToNotify.Unmarshal(m, b)
}
func (m *SubscriberToNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriberToNotify.Marshal(b, m, deterministic)
}
func (m *SubscriberToNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriberToNotify.Merge(m, src)
}
func (m *SubscriberToNotify) XXX_Size() int {
	return xxx_messageInfo_SubscriberToNotify.Size(m)
}
func (m *SubscriberToNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriberToNotify.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriberToNotify proto.InternalMessageInfo

func (m *SubscriberToNotify) GetSubscriptions() []*SubscriptionState {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *SubscriberToNotify) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Specification of a geographic area that a client is interested in on an ongoing basis (e.g., “planning area”).  Internal to the DSS.
type Subscription struct {
	Begins    *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=begins,proto3" json:"begins,omitempty"`
	Callbacks *SubscriptionCallbacks `protobuf:"bytes,2,opt,name=callbacks,proto3" json:"callbacks,omitempty"`
	// If set, this subscription will be automatically removed after this time.  RFC 3339 format, per OpenAPI specification.
	Expires           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	Id                string               `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	NotificationIndex int32                `protobuf:"varint,5,opt,name=notification_index,json=notificationIndex,proto3" json:"notification_index,omitempty"`
	// Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner.
	Owner                string   `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Version              string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{23}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetBegins() *timestamp.Timestamp {
	if m != nil {
		return m.Begins
	}
	return nil
}

func (m *Subscription) GetCallbacks() *SubscriptionCallbacks {
	if m != nil {
		return m.Callbacks
	}
	return nil
}

func (m *Subscription) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetNotificationIndex() int32 {
	if m != nil {
		return m.NotificationIndex
	}
	return 0
}

func (m *Subscription) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Subscription) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Endpoints that should be called when an applicable event occurs.  At least one field must be specified.
type SubscriptionCallbacks struct {
	IdentificationServiceAreaUrl string   `protobuf:"bytes,1,opt,name=identification_service_area_url,json=identificationServiceAreaUrl,proto3" json:"identification_service_area_url,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *SubscriptionCallbacks) Reset()         { *m = SubscriptionCallbacks{} }
func (m *SubscriptionCallbacks) String() string { return proto.CompactTextString(m) }
func (*SubscriptionCallbacks) ProtoMessage()    {}
func (*SubscriptionCallbacks) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{24}
}

func (m *SubscriptionCallbacks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionCallbacks.Unmarshal(m, b)
}
func (m *SubscriptionCallbacks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionCallbacks.Marshal(b, m, deterministic)
}
func (m *SubscriptionCallbacks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionCallbacks.Merge(m, src)
}
func (m *SubscriptionCallbacks) XXX_Size() int {
	return xxx_messageInfo_SubscriptionCallbacks.Size(m)
}
func (m *SubscriptionCallbacks) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionCallbacks.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionCallbacks proto.InternalMessageInfo

func (m *SubscriptionCallbacks) GetIdentificationServiceAreaUrl() string {
	if m != nil {
		return m.IdentificationServiceAreaUrl
	}
	return ""
}

// State of AreaSubscription which is causing a notification to be sent.
type SubscriptionState struct {
	NotificationIndex    int32    `protobuf:"varint,1,opt,name=notification_index,json=notificationIndex,proto3" json:"notification_index,omitempty"`
	Subscription         string   `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriptionState) Reset()         { *m = SubscriptionState{} }
func (m *SubscriptionState) String() string { return proto.CompactTextString(m) }
func (*SubscriptionState) ProtoMessage()    {}
func (*SubscriptionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{25}
}

func (m *SubscriptionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionState.Unmarshal(m, b)
}
func (m *SubscriptionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionState.Marshal(b, m, deterministic)
}
func (m *SubscriptionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionState.Merge(m, src)
}
func (m *SubscriptionState) XXX_Size() int {
	return xxx_messageInfo_SubscriptionState.Size(m)
}
func (m *SubscriptionState) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionState.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionState proto.InternalMessageInfo

func (m *SubscriptionState) GetNotificationIndex() int32 {
	if m != nil {
		return m.NotificationIndex
	}
	return 0
}

func (m *SubscriptionState) GetSubscription() string {
	if m != nil {
		return m.Subscription
	}
	return ""
}

// A three-dimensional geographic volume consisting of a vertically-extruded polygon.
type Volume3D struct {
	AltitudeHi           *wrappers.FloatValue `protobuf:"bytes,1,opt,name=altitude_hi,json=altitudeHi,proto3" json:"altitude_hi,omitempty"`
	AltitudeLo           *wrappers.FloatValue `protobuf:"bytes,2,opt,name=altitude_lo,json=altitudeLo,proto3" json:"altitude_lo,omitempty"`
	Footprint            *GeoPolygon          `protobuf:"bytes,3,opt,name=footprint,proto3" json:"footprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Volume3D) Reset()         { *m = Volume3D{} }
func (m *Volume3D) String() string { return proto.CompactTextString(m) }
func (*Volume3D) ProtoMessage()    {}
func (*Volume3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{26}
}

func (m *Volume3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume3D.Unmarshal(m, b)
}
func (m *Volume3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume3D.Marshal(b, m, deterministic)
}
func (m *Volume3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume3D.Merge(m, src)
}
func (m *Volume3D) XXX_Size() int {
	return xxx_messageInfo_Volume3D.Size(m)
}
func (m *Volume3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume3D.DiscardUnknown(m)
}

var xxx_messageInfo_Volume3D proto.InternalMessageInfo

func (m *Volume3D) GetAltitudeHi() *wrappers.FloatValue {
	if m != nil {
		return m.AltitudeHi
	}
	return nil
}

func (m *Volume3D) GetAltitudeLo() *wrappers.FloatValue {
	if m != nil {
		return m.AltitudeLo
	}
	return nil
}

func (m *Volume3D) GetFootprint() *GeoPolygon {
	if m != nil {
		return m.Footprint
	}
	return nil
}

// Contiguous block of geographic spacetime.
type Volume4D struct {
	SpatialVolume *Volume3D `protobuf:"bytes,1,opt,name=spatial_volume,json=spatialVolume,proto3" json:"spatial_volume,omitempty"`
	// End time of this volume.  RFC 3339 format, per OpenAPI specification.
	TimeEnd *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// Beginning time of this volume.  RFC 3339 format, per OpenAPI specification.
	TimeStart            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Volume4D) Reset()         { *m = Volume4D{} }
func (m *Volume4D) String() string { return proto.CompactTextString(m) }
func (*Volume4D) ProtoMessage()    {}
func (*Volume4D) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b4bd547de77484, []int{27}
}

func (m *Volume4D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume4D.Unmarshal(m, b)
}
func (m *Volume4D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume4D.Marshal(b, m, deterministic)
}
func (m *Volume4D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume4D.Merge(m, src)
}
func (m *Volume4D) XXX_Size() int {
	return xxx_messageInfo_Volume4D.Size(m)
}
func (m *Volume4D) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume4D.DiscardUnknown(m)
}

var xxx_messageInfo_Volume4D proto.InternalMessageInfo

func (m *Volume4D) GetSpatialVolume() *Volume3D {
	if m != nil {
		return m.SpatialVolume
	}
	return nil
}

func (m *Volume4D) GetTimeEnd() *timestamp.Timestamp {
	if m != nil {
		return m.TimeEnd
	}
	return nil
}

func (m *Volume4D) GetTimeStart() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStart
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteIdentificationServiceAreaRequest)(nil), "dssproto.DeleteIdentificationServiceAreaRequest")
	proto.RegisterType((*DeleteIdentificationServiceAreaResponse)(nil), "dssproto.DeleteIdentificationServiceAreaResponse")
	proto.RegisterType((*DeleteSubscriptionRequest)(nil), "dssproto.DeleteSubscriptionRequest")
	proto.RegisterType((*DeleteSubscriptionResponse)(nil), "dssproto.DeleteSubscriptionResponse")
	proto.RegisterType((*ErrorResponse)(nil), "dssproto.ErrorResponse")
	proto.RegisterType((*GeoPolygon)(nil), "dssproto.GeoPolygon")
	proto.RegisterType((*GetIdentificationServiceAreaRequest)(nil), "dssproto.GetIdentificationServiceAreaRequest")
	proto.RegisterType((*GetIdentificationServiceAreaResponse)(nil), "dssproto.GetIdentificationServiceAreaResponse")
	proto.RegisterType((*GetSubscriptionRequest)(nil), "dssproto.GetSubscriptionRequest")
	proto.RegisterType((*GetSubscriptionResponse)(nil), "dssproto.GetSubscriptionResponse")
	proto.RegisterType((*IdentificationServiceArea)(nil), "dssproto.IdentificationServiceArea")
	proto.RegisterType((*LatLngPoint)(nil), "dssproto.LatLngPoint")
	proto.RegisterType((*PutIdentificationServiceAreaParameters)(nil), "dssproto.PutIdentificationServiceAreaParameters")
	proto.RegisterType((*PutIdentificationServiceAreaRequest)(nil), "dssproto.PutIdentificationServiceAreaRequest")
	proto.RegisterType((*PutIdentificationServiceAreaResponse)(nil), "dssproto.PutIdentificationServiceAreaResponse")
	proto.RegisterType((*PutSubscriptionParameters)(nil), "dssproto.PutSubscriptionParameters")
	proto.RegisterType((*PutSubscriptionRequest)(nil), "dssproto.PutSubscriptionRequest")
	proto.RegisterType((*PutSubscriptionResponse)(nil), "dssproto.PutSubscriptionResponse")
	proto.RegisterType((*SearchIdentificationServiceAreasRequest)(nil), "dssproto.SearchIdentificationServiceAreasRequest")
	proto.RegisterType((*SearchIdentificationServiceAreasResponse)(nil), "dssproto.SearchIdentificationServiceAreasResponse")
	proto.RegisterType((*SearchSubscriptionsRequest)(nil), "dssproto.SearchSubscriptionsRequest")
	proto.RegisterType((*SearchSubscriptionsResponse)(nil), "dssproto.SearchSubscriptionsResponse")
	proto.RegisterType((*SubscriberToNotify)(nil), "dssproto.SubscriberToNotify")
	proto.RegisterType((*Subscription)(nil), "dssproto.Subscription")
	proto.RegisterType((*SubscriptionCallbacks)(nil), "dssproto.SubscriptionCallbacks")
	proto.RegisterType((*SubscriptionState)(nil), "dssproto.SubscriptionState")
	proto.RegisterType((*Volume3D)(nil), "dssproto.Volume3D")
	proto.RegisterType((*Volume4D)(nil), "dssproto.Volume4D")
}

func init() { proto.RegisterFile("pkg/dssproto/dss.proto", fileDescriptor_e6b4bd547de77484) }

var fileDescriptor_e6b4bd547de77484 = []byte{
	// 1317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0x9d, 0xe6, 0x67, 0xcf, 0x26, 0x2d, 0x1d, 0xda, 0x74, 0xe3, 0x44, 0x24, 0x71, 0x42,
	0x9b, 0x56, 0x74, 0xd3, 0x6e, 0x5b, 0xa4, 0xfe, 0x40, 0x55, 0x91, 0xf4, 0x47, 0xaa, 0x50, 0xe4,
	0x6d, 0x2b, 0x24, 0x24, 0x56, 0xb3, 0xbb, 0xb3, 0xdb, 0x51, 0xbd, 0xb6, 0x99, 0x99, 0x4d, 0x53,
	0x21, 0x28, 0x70, 0xcb, 0x15, 0xe2, 0x01, 0x90, 0xb8, 0xe0, 0x0e, 0x24, 0x24, 0x7e, 0x24, 0x5e,
	0x83, 0x17, 0xe0, 0x82, 0x6b, 0x9e, 0x01, 0x79, 0x76, 0xbc, 0x1e, 0xef, 0xda, 0x5e, 0x6f, 0xd5,
	0x0b, 0xee, 0xec, 0xe3, 0xef, 0xcc, 0x7c, 0xe7, 0x7c, 0x67, 0x8e, 0xcf, 0xc0, 0x72, 0xf0, 0xac,
	0xbb, 0xdb, 0xe6, 0x3c, 0x60, 0xbe, 0xf0, 0xc3, 0x87, 0xaa, 0x7c, 0x42, 0x0b, 0x91, 0xcd, 0x5a,
	0xeb, 0xfa, 0x7e, 0xd7, 0x25, 0xbb, 0x38, 0xa0, 0xbb, 0xd8, 0xf3, 0x7c, 0x81, 0x05, 0xf5, 0x3d,
	0x85, 0xb3, 0xd6, 0xd5, 0x57, 0xf9, 0xd6, 0xec, 0x77, 0x76, 0x05, 0xed, 0x11, 0x2e, 0x70, 0x2f,
	0x50, 0x80, 0xb7, 0x46, 0x01, 0xcf, 0x19, 0x0e, 0x02, 0xc2, 0xd4, 0x02, 0xb6, 0x03, 0x67, 0xf7,
	0x88, 0x4b, 0x04, 0x79, 0xd0, 0x26, 0x9e, 0xa0, 0x1d, 0xda, 0x92, 0xeb, 0xd7, 0x09, 0x3b, 0xa4,
	0x2d, 0x72, 0x87, 0x11, 0xec, 0x90, 0x4f, 0xfb, 0x84, 0x0b, 0x74, 0x1c, 0x4c, 0xda, 0xae, 0x18,
	0x1b, 0xc6, 0x4e, 0xc9, 0x31, 0x69, 0x1b, 0x55, 0x60, 0xfe, 0x90, 0x30, 0x4e, 0x7d, 0xaf, 0x62,
	0x4a, 0x63, 0xf4, 0x6a, 0xff, 0x62, 0xc0, 0xb9, 0x89, 0x8b, 0xf2, 0xc0, 0xf7, 0x38, 0x41, 0x77,
	0x61, 0x91, 0x0f, 0xcc, 0x0d, 0xcc, 0x08, 0x96, 0xeb, 0x97, 0x6b, 0x5b, 0xd5, 0x28, 0xfe, 0x6a,
	0xf6, 0x12, 0x65, 0x1e, 0xbf, 0xa0, 0xf7, 0xa1, 0xcc, 0xfb, 0x4d, 0xde, 0x62, 0xb4, 0x49, 0x18,
	0xaf, 0x98, 0x1b, 0x33, 0x3b, 0xe5, 0xda, 0x5a, 0xbc, 0x4c, 0x7d, 0xf8, 0xf1, 0x91, 0xff, 0xa1,
	0x2f, 0x68, 0xe7, 0x85, 0xa3, 0x3b, 0xd8, 0xfb, 0xb0, 0x32, 0xa0, 0xac, 0x80, 0x41, 0xb8, 0xdb,
	0xf4, 0xa1, 0x7f, 0x04, 0x56, 0xda, 0x32, 0x2a, 0xd8, 0x1b, 0xb0, 0xc8, 0x35, 0xbb, 0x0a, 0x76,
	0x79, 0x8c, 0xe5, 0xc0, 0x2b, 0x81, 0xb5, 0xcf, 0xc3, 0xd2, 0x3e, 0x63, 0x3e, 0x1b, 0x2e, 0x56,
	0x81, 0xf9, 0x1e, 0xe1, 0x1c, 0x77, 0x89, 0x62, 0x16, 0xbd, 0xda, 0xb7, 0x01, 0xee, 0x11, 0xff,
	0xc0, 0x77, 0x5f, 0x74, 0x7d, 0x0f, 0x5d, 0x86, 0x85, 0x43, 0xc2, 0x04, 0x6d, 0x11, 0x5e, 0x31,
	0x64, 0x5a, 0x4e, 0xc7, 0x1b, 0x3e, 0xc4, 0xe2, 0xa1, 0xd7, 0x3d, 0xf0, 0xa9, 0x27, 0x9c, 0x21,
	0xcc, 0xbe, 0x06, 0x5b, 0xf7, 0x88, 0x98, 0xb6, 0x22, 0xec, 0x6f, 0x0c, 0xd8, 0xce, 0xf7, 0x53,
	0xd4, 0x5b, 0xb0, 0x4a, 0x13, 0xa0, 0xc6, 0xab, 0xd6, 0xc0, 0x0a, 0xcd, 0xfa, 0x64, 0xef, 0xc0,
	0xf2, 0x3d, 0x22, 0x0a, 0xc8, 0x69, 0x3f, 0x86, 0x33, 0x63, 0xc8, 0xd7, 0xa0, 0xd8, 0xbf, 0x06,
	0xac, 0x64, 0x32, 0x47, 0xeb, 0x50, 0xee, 0xb8, 0xb4, 0xfb, 0x54, 0xf0, 0x46, 0x9f, 0xb9, 0x8a,
	0x0d, 0x28, 0xd3, 0x63, 0xe6, 0x2a, 0x96, 0xe6, 0xb0, 0xe8, 0x4e, 0xc1, 0xac, 0xff, 0xdc, 0x23,
	0xac, 0x32, 0x23, 0x4d, 0x83, 0x17, 0x74, 0x0d, 0x16, 0xc2, 0x23, 0xdf, 0x20, 0x5e, 0xbb, 0x72,
	0x4c, 0x92, 0xb3, 0xaa, 0x83, 0x23, 0x5f, 0x8d, 0x8e, 0x7c, 0xf5, 0x51, 0xd4, 0x13, 0x9c, 0xf9,
	0x10, 0xbb, 0xef, 0xb5, 0xd1, 0x75, 0x00, 0xe9, 0xc6, 0x05, 0x66, 0xa2, 0x32, 0x3b, 0xd1, 0xb1,
	0x14, 0xa2, 0xeb, 0x21, 0x58, 0x2f, 0xfe, 0xb9, 0x64, 0xf1, 0x5f, 0x86, 0xb2, 0x56, 0x4f, 0xe8,
	0x0d, 0x98, 0x71, 0xb1, 0x90, 0x91, 0x19, 0x4e, 0xf8, 0x28, 0x2d, 0x5e, 0x57, 0xc6, 0x14, 0x5a,
	0xbc, 0xae, 0xfd, 0xad, 0x01, 0x67, 0x0f, 0xfa, 0xd9, 0x25, 0x73, 0x80, 0x19, 0xee, 0x11, 0x41,
	0x18, 0x47, 0xef, 0xc0, 0x3c, 0x39, 0x12, 0xc4, 0x13, 0x5c, 0xa9, 0x80, 0x62, 0x15, 0x9e, 0xf8,
	0x6e, 0xbf, 0x47, 0xae, 0xee, 0x39, 0x11, 0x64, 0x34, 0xbd, 0xe6, 0x58, 0x7a, 0xb5, 0x30, 0x66,
	0x92, 0x61, 0xbc, 0x84, 0xad, 0x3c, 0x4a, 0x59, 0x4d, 0xe1, 0x3e, 0xcc, 0x05, 0x21, 0x5b, 0x2e,
	0x37, 0x2b, 0xd7, 0x2e, 0xc5, 0xf4, 0x8a, 0x45, 0xe8, 0x28, 0x7f, 0xfb, 0x67, 0x03, 0xb6, 0xf3,
	0x19, 0xfc, 0xcf, 0x9a, 0xe7, 0x0f, 0x06, 0xac, 0x1c, 0xf4, 0x13, 0x27, 0x48, 0x13, 0xee, 0x3d,
	0x28, 0xb5, 0xb0, 0xeb, 0x36, 0x71, 0xeb, 0x59, 0x24, 0xdd, 0x7a, 0xfa, 0x01, 0xfa, 0x20, 0x82,
	0x39, 0xb1, 0x87, 0xae, 0xbb, 0x39, 0x59, 0xf7, 0x6c, 0x59, 0x09, 0x2c, 0x8f, 0x70, 0xcc, 0x52,
	0xf2, 0xe6, 0x88, 0x92, 0x5b, 0x09, 0x25, 0xd3, 0xa3, 0x1c, 0x8a, 0xf7, 0xbd, 0x01, 0x67, 0xc6,
	0xf6, 0x51, 0x7a, 0xdd, 0x87, 0x25, 0x5d, 0xaf, 0xa8, 0x1f, 0x17, 0x12, 0x6c, 0x51, 0x13, 0x8c,
	0x8f, 0xf5, 0x25, 0x73, 0x8a, 0xbe, 0xf4, 0x95, 0x09, 0xe7, 0xea, 0x04, 0xb3, 0xd6, 0xd3, 0xcc,
	0xdd, 0x78, 0x94, 0x1a, 0x04, 0xc7, 0x86, 0x95, 0x55, 0x72, 0xe4, 0x33, 0xba, 0x0d, 0x4b, 0x04,
	0x33, 0x97, 0x12, 0x2e, 0x1a, 0x61, 0x5b, 0x50, 0x9b, 0xe7, 0xb5, 0x8f, 0xc5, 0xc8, 0x21, 0x34,
	0xa1, 0x9b, 0x50, 0x76, 0xb1, 0x18, 0xba, 0xcf, 0x4c, 0x74, 0x87, 0x01, 0x5c, 0x3a, 0x6f, 0xc2,
	0x62, 0x0f, 0x1f, 0x35, 0xb0, 0x2b, 0xa8, 0xe8, 0xb7, 0x89, 0x6c, 0x7a, 0x86, 0x53, 0xee, 0xe1,
	0xa3, 0x3b, 0xca, 0x24, 0x21, 0xd4, 0x8b, 0x21, 0xb3, 0x0a, 0x42, 0xbd, 0x08, 0x62, 0x0b, 0xd8,
	0x99, 0x9c, 0x82, 0xd7, 0xad, 0x9a, 0x7d, 0x09, 0xac, 0xc1, 0xae, 0xba, 0x3a, 0x79, 0xb9, 0xb6,
	0x3f, 0x86, 0xd5, 0x54, 0x0f, 0x45, 0xed, 0x16, 0x2c, 0xe9, 0xd2, 0x46, 0xd4, 0xb2, 0xea, 0x20,
	0x09, 0xb6, 0x29, 0xa0, 0xf1, 0x93, 0x8d, 0xee, 0xa4, 0xaf, 0xb9, 0x9a, 0xbe, 0x66, 0x5d, 0x60,
	0x41, 0x46, 0x16, 0x0e, 0xfb, 0x7c, 0xdc, 0x74, 0xc3, 0x47, 0xfb, 0x47, 0x13, 0x16, 0x75, 0x37,
	0x54, 0x83, 0xb9, 0x26, 0xe9, 0x52, 0x2f, 0xea, 0x08, 0x79, 0xf2, 0x2b, 0x64, 0xb2, 0x91, 0x98,
	0x53, 0x37, 0x92, 0xab, 0x61, 0x23, 0x09, 0x28, 0x23, 0xbc, 0x40, 0xc9, 0x45, 0x50, 0xd5, 0x1c,
	0x8e, 0x0d, 0x9b, 0xc3, 0x45, 0x40, 0x9e, 0xaf, 0x4d, 0x2e, 0xd4, 0x6b, 0x93, 0x23, 0x59, 0x62,
	0xb3, 0xce, 0x49, 0xfd, 0xcb, 0x83, 0xf0, 0x43, 0xfc, 0xd7, 0x9e, 0xd3, 0xff, 0xda, 0x5a, 0x97,
	0x9a, 0x4f, 0x76, 0xa9, 0x4f, 0xe0, 0x74, 0x6a, 0x20, 0x68, 0x1f, 0xd6, 0x73, 0x66, 0x26, 0x6d,
	0x86, 0x58, 0xcb, 0x1c, 0x89, 0x1e, 0x33, 0xd7, 0xee, 0xc0, 0xc9, 0x31, 0xf9, 0x32, 0x62, 0x32,
	0xb2, 0x62, 0xb2, 0x53, 0x9a, 0x4f, 0x69, 0xa4, 0xc9, 0xfc, 0x69, 0xc0, 0xc2, 0xa0, 0x3b, 0x5f,
	0xd9, 0x43, 0xb7, 0xa0, 0x1c, 0x1d, 0xc6, 0xc6, 0x53, 0xaa, 0x14, 0x5f, 0x1d, 0xcb, 0xfe, 0x5d,
	0xd7, 0xc7, 0xe2, 0x09, 0x76, 0xfb, 0xc4, 0x81, 0x08, 0x7f, 0x9f, 0x26, 0xbc, 0x5d, 0x5f, 0x09,
	0x5f, 0xcc, 0xfb, 0xa1, 0x8f, 0x6a, 0x50, 0xea, 0xf8, 0xbe, 0x08, 0x18, 0xf5, 0x84, 0xd2, 0xfd,
	0x54, 0x5c, 0x34, 0xf1, 0x9c, 0xec, 0xc4, 0x30, 0xfb, 0x8f, 0x21, 0xf9, 0xab, 0x7b, 0xe8, 0x3a,
	0x1c, 0xe7, 0x01, 0x16, 0x14, 0xbb, 0x8d, 0x43, 0x69, 0xcb, 0x1a, 0x3f, 0xae, 0xec, 0x39, 0x4b,
	0x0a, 0x39, 0x30, 0x24, 0x86, 0x33, 0xf3, 0x55, 0x87, 0xb3, 0x99, 0x29, 0x86, 0xb3, 0xda, 0xdf,
	0x25, 0x28, 0xed, 0xd5, 0x95, 0xe6, 0xe8, 0x77, 0x03, 0xd6, 0x27, 0x5c, 0xc4, 0x90, 0x36, 0xa6,
	0x14, 0xbb, 0x08, 0x5a, 0x97, 0xa7, 0xf0, 0x18, 0xf4, 0x29, 0xbb, 0xfa, 0xf5, 0x5f, 0xff, 0x7c,
	0x67, 0xee, 0x5c, 0x38, 0x1b, 0x5e, 0x71, 0x77, 0x73, 0xea, 0x98, 0xef, 0x7e, 0x46, 0xdb, 0x9f,
	0xa3, 0x2f, 0x0d, 0x40, 0xe3, 0xf7, 0x28, 0xb4, 0x35, 0xba, 0x73, 0xca, 0xdf, 0xdc, 0xda, 0xce,
	0x07, 0x29, 0x46, 0xeb, 0x92, 0xd1, 0xca, 0x85, 0x33, 0x92, 0x51, 0xa2, 0x7d, 0x0d, 0x28, 0xfc,
	0x64, 0xc0, 0x5a, 0xde, 0x65, 0x06, 0x5d, 0xd4, 0xab, 0x68, 0xe2, 0xb8, 0x68, 0x55, 0x8b, 0xc2,
	0x93, 0x29, 0x43, 0x45, 0x53, 0xf6, 0x1c, 0x4e, 0x8c, 0x5c, 0x62, 0xd0, 0x46, 0x62, 0xcb, 0xb4,
	0x5c, 0x6d, 0xe6, 0x20, 0x92, 0x89, 0x42, 0x99, 0x89, 0xfa, 0xcd, 0x80, 0xb5, 0xbc, 0x69, 0x55,
	0x4f, 0x54, 0x81, 0xb9, 0x5a, 0x4f, 0x54, 0x91, 0x21, 0xd8, 0x7e, 0x57, 0x12, 0xbc, 0x64, 0x15,
	0x4c, 0xd4, 0x0d, 0x35, 0xa8, 0xa1, 0x97, 0x70, 0x62, 0x64, 0x4e, 0xd3, 0x13, 0x96, 0x3e, 0x2a,
	0xea, 0x09, 0xcb, 0x18, 0xf2, 0xec, 0x73, 0x92, 0xcf, 0xa6, 0x95, 0x95, 0xb0, 0x21, 0x81, 0x5f,
	0x0d, 0xd8, 0x98, 0x34, 0x84, 0x20, 0xed, 0xb0, 0x15, 0x9c, 0xd9, 0xac, 0xda, 0x34, 0x2e, 0x8a,
	0xf4, 0x79, 0x49, 0x7a, 0x0b, 0x6d, 0x4e, 0x4c, 0x22, 0xfa, 0x02, 0xde, 0x4c, 0x19, 0x49, 0xd0,
	0xf6, 0xe8, 0xae, 0x69, 0x33, 0x8e, 0xf5, 0xf6, 0x04, 0x94, 0xa2, 0x63, 0x49, 0x3a, 0xa7, 0x10,
	0x1a, 0xcf, 0x61, 0x73, 0x4e, 0xba, 0x5f, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x62, 0xb0,
	0xb9, 0x3b, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DSServiceClient is the client API for DSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSServiceClient interface {
	// /dss/identification_service_areas/{id}
	//
	// Delete an Identification Service Area.  USSs should not delete Identification Service Areas before the end of the last managed flight plus the retention period.
	DeleteIdentificationServiceArea(ctx context.Context, in *DeleteIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*DeleteIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Delete a subscription.
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	// /dss/identification_service_areas/{id}
	//
	// Verify the existence/valdity and state of a particular IdentificationServiceArea.
	GetIdentificationServiceArea(ctx context.Context, in *GetIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*GetIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Verify the existence/valdity and state of a particular subscription.
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	// /dss/identification_service_areas/{id}
	//
	// Create or update an Identification Service Area.
	//
	// The DSS assumes the USS has already added the appropriate retention period to operation end time in `time_end` field before storing it.  Updating `time_start` is not allowed if it is before the current time.
	PutIdentificationServiceArea(ctx context.Context, in *PutIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*PutIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Create or update a subscription.  Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	PutSubscription(ctx context.Context, in *PutSubscriptionRequest, opts ...grpc.CallOption) (*PutSubscriptionResponse, error)
	// /dss/identification_service_areas
	//
	// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
	SearchIdentificationServiceAreas(ctx context.Context, in *SearchIdentificationServiceAreasRequest, opts ...grpc.CallOption) (*SearchIdentificationServiceAreasResponse, error)
	// /dss/subscriptions
	//
	// Retrieve subscriptions intersecting an area of interest.  Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Only Subscriptions belonging to the caller are returned.  This endpoint would be used if a USS lost track of Subscriptions they had created and/or wanted to resolve an error indicating that they had too many existing Subscriptions in an area.
	SearchSubscriptions(ctx context.Context, in *SearchSubscriptionsRequest, opts ...grpc.CallOption) (*SearchSubscriptionsResponse, error)
}

type dSServiceClient struct {
	cc *grpc.ClientConn
}

func NewDSServiceClient(cc *grpc.ClientConn) DSServiceClient {
	return &dSServiceClient{cc}
}

func (c *dSServiceClient) DeleteIdentificationServiceArea(ctx context.Context, in *DeleteIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*DeleteIdentificationServiceAreaResponse, error) {
	out := new(DeleteIdentificationServiceAreaResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/DeleteIdentificationServiceArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) GetIdentificationServiceArea(ctx context.Context, in *GetIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*GetIdentificationServiceAreaResponse, error) {
	out := new(GetIdentificationServiceAreaResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/GetIdentificationServiceArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/GetSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) PutIdentificationServiceArea(ctx context.Context, in *PutIdentificationServiceAreaRequest, opts ...grpc.CallOption) (*PutIdentificationServiceAreaResponse, error) {
	out := new(PutIdentificationServiceAreaResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/PutIdentificationServiceArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) PutSubscription(ctx context.Context, in *PutSubscriptionRequest, opts ...grpc.CallOption) (*PutSubscriptionResponse, error) {
	out := new(PutSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/PutSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) SearchIdentificationServiceAreas(ctx context.Context, in *SearchIdentificationServiceAreasRequest, opts ...grpc.CallOption) (*SearchIdentificationServiceAreasResponse, error) {
	out := new(SearchIdentificationServiceAreasResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/SearchIdentificationServiceAreas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSServiceClient) SearchSubscriptions(ctx context.Context, in *SearchSubscriptionsRequest, opts ...grpc.CallOption) (*SearchSubscriptionsResponse, error) {
	out := new(SearchSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/dssproto.DSService/SearchSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSServiceServer is the server API for DSService service.
type DSServiceServer interface {
	// /dss/identification_service_areas/{id}
	//
	// Delete an Identification Service Area.  USSs should not delete Identification Service Areas before the end of the last managed flight plus the retention period.
	DeleteIdentificationServiceArea(context.Context, *DeleteIdentificationServiceAreaRequest) (*DeleteIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Delete a subscription.
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	// /dss/identification_service_areas/{id}
	//
	// Verify the existence/valdity and state of a particular IdentificationServiceArea.
	GetIdentificationServiceArea(context.Context, *GetIdentificationServiceAreaRequest) (*GetIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Verify the existence/valdity and state of a particular subscription.
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error)
	// /dss/identification_service_areas/{id}
	//
	// Create or update an Identification Service Area.
	//
	// The DSS assumes the USS has already added the appropriate retention period to operation end time in `time_end` field before storing it.  Updating `time_start` is not allowed if it is before the current time.
	PutIdentificationServiceArea(context.Context, *PutIdentificationServiceAreaRequest) (*PutIdentificationServiceAreaResponse, error)
	// /dss/subscriptions/{id}
	//
	// Create or update a subscription.  Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	PutSubscription(context.Context, *PutSubscriptionRequest) (*PutSubscriptionResponse, error)
	// /dss/identification_service_areas
	//
	// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
	SearchIdentificationServiceAreas(context.Context, *SearchIdentificationServiceAreasRequest) (*SearchIdentificationServiceAreasResponse, error)
	// /dss/subscriptions
	//
	// Retrieve subscriptions intersecting an area of interest.  Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Only Subscriptions belonging to the caller are returned.  This endpoint would be used if a USS lost track of Subscriptions they had created and/or wanted to resolve an error indicating that they had too many existing Subscriptions in an area.
	SearchSubscriptions(context.Context, *SearchSubscriptionsRequest) (*SearchSubscriptionsResponse, error)
}

// UnimplementedDSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDSServiceServer struct {
}

func (*UnimplementedDSServiceServer) DeleteIdentificationServiceArea(ctx context.Context, req *DeleteIdentificationServiceAreaRequest) (*DeleteIdentificationServiceAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIdentificationServiceArea not implemented")
}
func (*UnimplementedDSServiceServer) DeleteSubscription(ctx context.Context, req *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (*UnimplementedDSServiceServer) GetIdentificationServiceArea(ctx context.Context, req *GetIdentificationServiceAreaRequest) (*GetIdentificationServiceAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentificationServiceArea not implemented")
}
func (*UnimplementedDSServiceServer) GetSubscription(ctx context.Context, req *GetSubscriptionRequest) (*GetSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (*UnimplementedDSServiceServer) PutIdentificationServiceArea(ctx context.Context, req *PutIdentificationServiceAreaRequest) (*PutIdentificationServiceAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutIdentificationServiceArea not implemented")
}
func (*UnimplementedDSServiceServer) PutSubscription(ctx context.Context, req *PutSubscriptionRequest) (*PutSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutSubscription not implemented")
}
func (*UnimplementedDSServiceServer) SearchIdentificationServiceAreas(ctx context.Context, req *SearchIdentificationServiceAreasRequest) (*SearchIdentificationServiceAreasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchIdentificationServiceAreas not implemented")
}
func (*UnimplementedDSServiceServer) SearchSubscriptions(ctx context.Context, req *SearchSubscriptionsRequest) (*SearchSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSubscriptions not implemented")
}

func RegisterDSServiceServer(s *grpc.Server, srv DSServiceServer) {
	s.RegisterService(&_DSService_serviceDesc, srv)
}

func _DSService_DeleteIdentificationServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIdentificationServiceAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).DeleteIdentificationServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/DeleteIdentificationServiceArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).DeleteIdentificationServiceArea(ctx, req.(*DeleteIdentificationServiceAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_GetIdentificationServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentificationServiceAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).GetIdentificationServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/GetIdentificationServiceArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).GetIdentificationServiceArea(ctx, req.(*GetIdentificationServiceAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/GetSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_PutIdentificationServiceArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIdentificationServiceAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).PutIdentificationServiceArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/PutIdentificationServiceArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).PutIdentificationServiceArea(ctx, req.(*PutIdentificationServiceAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_PutSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).PutSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/PutSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).PutSubscription(ctx, req.(*PutSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_SearchIdentificationServiceAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIdentificationServiceAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).SearchIdentificationServiceAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/SearchIdentificationServiceAreas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).SearchIdentificationServiceAreas(ctx, req.(*SearchIdentificationServiceAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSService_SearchSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSServiceServer).SearchSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dssproto.DSService/SearchSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSServiceServer).SearchSubscriptions(ctx, req.(*SearchSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dssproto.DSService",
	HandlerType: (*DSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteIdentificationServiceArea",
			Handler:    _DSService_DeleteIdentificationServiceArea_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _DSService_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetIdentificationServiceArea",
			Handler:    _DSService_GetIdentificationServiceArea_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _DSService_GetSubscription_Handler,
		},
		{
			MethodName: "PutIdentificationServiceArea",
			Handler:    _DSService_PutIdentificationServiceArea_Handler,
		},
		{
			MethodName: "PutSubscription",
			Handler:    _DSService_PutSubscription_Handler,
		},
		{
			MethodName: "SearchIdentificationServiceAreas",
			Handler:    _DSService_SearchIdentificationServiceAreas_Handler,
		},
		{
			MethodName: "SearchSubscriptions",
			Handler:    _DSService_SearchSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/dssproto/dss.proto",
}
