{
 "title": "Cockroach Runtime",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "Cluster name",
    "query": "sys_uptime{app=\"cockroachdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{app=\"cockroachdb\"},pod_name)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Nodes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Built Timestamp",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "build_timestamp{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sys_uptime{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sys_uptime{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Memory: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sys_rss{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(sys_go_allocbytes{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "RSS: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sys_rss{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sys_goroutines{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"})",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Goroutines: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sys_goroutines{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "GC: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_gc_count{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Runs"
    },
    {
     "expr": "sum(rate(sys_gc_pause_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]))",
     "legendFormat": "GC Pauses"
    }
   ]
  },
  {
   "title": "GC Pauses: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(sys_gc_pause_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU Time: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(sys_cpu_user_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]) + rate(sys_cpu_sys_ns{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sys_cgocalls{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval]))",
     "legendFormat": "calls/sec"
    }
   ]
  },
  {
   "title": "CGo Calls: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "rate(sys_cgocalls{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Mean RPC Clock Offset: $node",
   "type": "graph",
   "description": "Mean clock offset with other nodes as measured by cockroach.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "clock_offset_meannanos{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\", pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Clock Offset: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "clock_offset_meannanos{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\", pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 50th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_50{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 95th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_95{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Round Trip Latency: 99th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "round_trip_latency:rate1m:quantile_99{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  }
 ]
}