{
 "title": "Cockroach Replicas",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "Cluster name",
    "query": "sys_uptime{app=\"cockroachdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{app=\"cockroachdb\",k8s_cluster=~\"^$k8s_cluster.*$\"},pod_name)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "raft leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "raft leaders not lease holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "Ranges: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(ranges{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}} - ranges"
    },
    {
     "expr": "sum(ranges_unavailable{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}} - unavailable"
    }
   ]
  },
  {
   "title": "Raft Log: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raftlog_behind{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "raft log behind"
    },
    {
     "expr": "sum(sum(rate(raftlog_truncated{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "raft log truncated"
    },
    {
     "expr": "sum(sum(raftlog_selfbehind{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "raft log self behind"
    }
   ]
  },
  {
   "title": "Raft Log Behind: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(raftlog_behind{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster))",
     "legendFormat": "Quiescent"
    },
    {
     "expr": "sum(sum(replicas{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster) - sum(replicas_quiescent{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Quiescent Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(replicas_quiescent{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Replicas per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(replicas{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Logical bytes per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(keybytes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster) + sum(valbytes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Live bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(livebytes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Keys written per second per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Keys written per second: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "splits"
    },
    {
     "expr": "sum(sum(rate(range_adds{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "removes"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(range_splits{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster) + sum(rate(range_adds{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster) + sum(rate(range_removes{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}}"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_snapshots_generated{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_normal_applied{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "Normal-applied"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_preemptive_applied{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster))",
     "legendFormat": "Preemptive-applied"
    },
    {
     "expr": "sum(replicas_reserved{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"})",
     "legendFormat": "Reservations"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}} - generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster) + sum(rate(range_snapshots_preemptive_applied{k8s_cluster=~\"^$k8s_cluster.*$\",app=\"cockroachdb\",pod_name=~\"$node\"}[$rate_interval])) by (pod_name, k8s_cluster)",
     "legendFormat": "{{pod_name}}-{{k8s_cluster}} - applied"
    }
   ]
  }
 ]
}