# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Definition for Docker image that proxies HTTPS traffic to the auth server.

# To build an image from this Dockerfile:
# docker image build -f Dockerfile_authreverseproxy -t interussplatform/auth_reverse_proxy .

# To run this image, cert.pem and key.pem must be provided for HTTPS.  See the README for how to
# generate these files.  Then, run the container with:
# docker run \
#     -e INTERUSS_AUTH_SERVER="auth_server_ip" -e INTERUSS_AUTH_PORT="5000" \
#     -p 8121:8121 -d interussplatform/auth_reverse_proxy
#     -v /local/path/to/cert:/etc/ssl/certs
#     -v /local/path/to/key:/etc/ssl/private

# Required environment variables:
#   INTERUSS_AUTH_SERVER: Address of the auth server.
#   INTERUSS_AUTH_PORT: Port on which the auth server is listening.

# Optional environment variables:
#   INTERUSS_API_PORT_HTTPS: Port on which the InterUSS API will be served via HTTPS (default 8121).

FROM nginx

COPY nginx_entrypoint.sh .

ENV INTERUSS_AUTH_PORT_HTTPS 8121

CMD ./nginx_entrypoint.sh

EXPOSE $INTERUSS_AUTH_PORT_HTTPS
