@startuml
title Geo-Awareness

participant TD as "Test driver"
participant U as "USS under Test"

== Test setup: Load the geozones dataset ==
TD -> U: PUT /geozones/{geozones_id}
TD <- U: 200 Ok - Geozones loading\n{"result": "Processing"}

TD -> U: GET /geozones/{geozones_id}
TD <- U: 200 Ok - Geozones still loading\n{"result": "Processing"}

...

TD -> U: GET /geozones/{geozones_id}
TD <- U: 200 Ok - Geozones ready\n{"result": "Ready"}

== Query the USS for Geo-Awareness information ==

TD -> U: GET /checklist
TD <- U: 200 Ok - Returns the list of Geo-Awareness information\nfor a specific Volume4D.

== Test tear down: Delete the Geozones dataset ==

TD -> U: DELETE /geozones/{geozones_id}
TD <- U: 200 Ok - {"result": "Deleting"}

TD -> U: GET /geozones/{geozones_id}
TD <- U: 200 Ok - {"result": "Deleting"}

...

TD -> U: GET /geozones/{geozones_id}
TD <- U: 404 NotFound

@enduml