// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/raftstore/consensus/proposalpb/proposal.proto

package proposalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proposal struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId             uint64                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TimestampUnixNanos int64                  `protobuf:"fixed64,3,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	RequestType        string                 `protobuf:"bytes,4,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	Value              []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	ReadOnly           bool                   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Compressed         bool                   `protobuf:"varint,7,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_pkg_raftstore_consensus_proposalpb_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_raftstore_consensus_proposalpb_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Proposal) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Proposal) GetTimestampUnixNanos() int64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *Proposal) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *Proposal) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Proposal) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Proposal) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

var File_pkg_raftstore_consensus_proposalpb_proposal_proto protoreflect.FileDescriptor

const file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDesc = "" +
	"\n" +
	"1pkg/raftstore/consensus/proposalpb/proposal.proto\x12\x17dss.raftstore.consensus\"\xdb\x01\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeId\x120\n" +
	"\x14timestamp_unix_nanos\x18\x03 \x01(\x10R\x12timestampUnixNanos\x12!\n" +
	"\frequest_type\x18\x04 \x01(\tR\vrequestType\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\x12\x1e\n" +
	"\n" +
	"compressed\x18\a \x01(\bR\n" +
	"compressedB<Z:github.com/interuss/dss/pkg/raftstore/consensus/proposalpbb\x06proto3"

var (
	file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescOnce sync.Once
	file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescData []byte
)

func file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescGZIP() []byte {
	file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescOnce.Do(func() {
		file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDesc), len(file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDesc)))
	})
	return file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDescData
}

var file_pkg_raftstore_consensus_proposalpb_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_raftstore_consensus_proposalpb_proposal_proto_goTypes = []any{
	(*Proposal)(nil), // 0: dss.raftstore.consensus.Proposal
}
var file_pkg_raftstore_consensus_proposalpb_proposal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_raftstore_consensus_proposalpb_proposal_proto_init() }
func file_pkg_raftstore_consensus_proposalpb_proposal_proto_init() {
	if File_pkg_raftstore_consensus_proposalpb_proposal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDesc), len(file_pkg_raftstore_consensus_proposalpb_proposal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_raftstore_consensus_proposalpb_proposal_proto_goTypes,
		DependencyIndexes: file_pkg_raftstore_consensus_proposalpb_proposal_proto_depIdxs,
		MessageInfos:      file_pkg_raftstore_consensus_proposalpb_proposal_proto_msgTypes,
	}.Build()
	File_pkg_raftstore_consensus_proposalpb_proposal_proto = out.File
	file_pkg_raftstore_consensus_proposalpb_proposal_proto_goTypes = nil
	file_pkg_raftstore_consensus_proposalpb_proposal_proto_depIdxs = nil
}
