'To render with PlantUML:
'  java -jar plantuml.jar -o generated atproxy_sequence.puml
@startuml
participant "Internal DP system" as IS
participant "Internal automated testing client" as IC
participant "atproxy" as atp
participant "uss_qualifier" as Q
IC -> atp: Any requests?
Note over atp: Some time elapses
atp --> IC: No requests right now
IC -> atp: Any requests?
Q -> atp: GET /observation/display_data
Note over atp: Stores request
atp --> IC: 1 request available
Note over IC: Parse request as display_data request
IC -> IS: (pretending to be Display Application)\nGet flights in specified view
IS --> IC: Flight and/or cluster list
IC -> atp: Request fulfillment
atp --> IC: Ok
atp --> Q: Flights and clusters
@enduml
