nav:
  - "Overview": index.md
  - "Leaving a CockroachDB pool": depooling-crdb.md
  - "Leaving a YugabyteDB pool": depooling-yugabyte.md
  - "After terraform": after-terraform.md
  - "Minikube": minikube.md
