from monitoring.prober.rid.v1 import common as common_v1


VERTICES = common_v1.VERTICES
GEO_POLYGON_STRING = common_v1.GEO_POLYGON_STRING
HUGE_GEO_POLYGON_STRING = common_v1.HUGE_GEO_POLYGON_STRING
LOOP_GEO_POLYGON_STRING = common_v1.LOOP_GEO_POLYGON_STRING
HUGE_VERTICES = common_v1.HUGE_VERTICES
