#!/bin/sh

export INTERUSS_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
<<REPLACE WITH YOUR PUBLIC KEY>>
-----END PUBLIC KEY-----"

export INTERUSS_CONNECTIONSTRING="localhost:2181"
export INTERUSS_API_SERVER=0.0.0.0
export INTERUSS_API_PORT=8121
export INTERUSS_VERBOSE=true

export STORAGE_API_ARGS="-t sandbox"

