nav:
  - "Overview": index.md
  - "Database cleanup": cleanup.md
  - "Monitoring": monitoring.md
  - "Health checks": healthchecks.md
  - "Performance": performance.md
  - "Database migrations": database-migrations.md
  - "DSS upgrades": upgrades.md
  - "CockroachDB version upgrades": crdb-upgrades.md
  - "Kubernetes upgrades": kubernetes-upgrades.md
  - "Leaving a pool": pooling.md
  - "Troubleshooting": troubleshooting.md
