nav:
  - "Overview": index.md
  - "Database cleanup": cleanup.md
  - "Monitoring": monitoring.md
  - "Health checks": healthchecks.md
  - "Performance": performance.md
  - "Database migration": db-migration.md
  - "Pooling": pooling.md
  - "Upgrading Kubernetes": kubernetes-upgrades.md
  - "Upgrading CockroachDB": crdb-upgrades.md
  - "Troubleshooting": troubleshooting.md
