nav:
  - "Getting Started": index.md
  - "Deploy a DSS instance": deployment/
  - "Operate a DSS instance": operations/
  - "Decommission a DSS instance": decommissioning/
  - "Background": background/
