@startuml
center header Strategic Coordination Interoperability
title Nominal test

participant "Test Driver" as TD
participant "USS1 under test" as USS1
participant "USS2 under test" as USS2
participant "DSS"

== TD injects via USS1 non-conflicting Operational Intent 1 ==

TD -> USS1: PUT /inject/flight
TD <- USS1: 200 Ok - Operational Intent 1 created\n{"result": "planned"}

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing Operational Intent 1
TD <- DSS: 200 Ok - returns Operational Intent Reference 1 with entityid1 managed by USS1

TD -> USS1: GET /uss/v1/operational_intents/{entityid1}
TD <- USS1: 200 Ok - returns Operational Intent 1

...

== TD injects via USS2 a conflicting Operational Intent (time, altitude, priority or area) ==

TD -> USS2: PUT /inject/flight
TD <- USS2: 200 Ok\n{"result": "conflict"}

@enduml
