@startuml
title Geo-Awareness

participant TD as "Test driver"
participant U as "USS under Test"

== Test setup: Load the Geozones dataset ==
TD -> U: PUT /geozone_sources/{geozone_source_id}
TD <- U: 200 Ok - Geozones loading\n{"result": "Activating"}

TD -> U: GET /geozone_sources/{geozone_source_id}
TD <- U: 200 Ok - Geozones still loading\n{"result": "Activating"}

...

TD -> U: GET /geozone_sources/{geozone_source_id}
TD <- U: 200 Ok - Geozones ready\n{"result": "Ready"}

== Query the USS for Geo-Awareness information ==

TD -> U: GET /checklist
TD <- U: 200 Ok - Returns a list of advisories and restrictions (when applicable) for the specified flight

== Test teardown: Delete the Geozones dataset ==

TD -> U: DELETE /geozone_sources/{geozone_source_id}
TD <- U: 200 Ok - {"result": "Deactivating"}

TD -> U: GET /geozone_sources/{geozone_source_id}
TD <- U: 200 Ok - {"result": "Deactivating"}

...

TD -> U: GET /geozone_sources/{geozone_source_id}
TD <- U: 404 NotFound

@enduml
