// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote_id.proto

package dssproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteUASReporterRequest struct {
	// EntityUUID of the Entity.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUASReporterRequest) Reset()         { *m = DeleteUASReporterRequest{} }
func (m *DeleteUASReporterRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUASReporterRequest) ProtoMessage()    {}
func (*DeleteUASReporterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{0}
}

func (m *DeleteUASReporterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUASReporterRequest.Unmarshal(m, b)
}
func (m *DeleteUASReporterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUASReporterRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUASReporterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUASReporterRequest.Merge(m, src)
}
func (m *DeleteUASReporterRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUASReporterRequest.Size(m)
}
func (m *DeleteUASReporterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUASReporterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUASReporterRequest proto.InternalMessageInfo

func (m *DeleteUASReporterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response for a request to delete an Entity.
type DeleteUASReporterResponse struct {
	// DSS reference to Entity that was just deleted.
	PreReference *UASReporter `protobuf:"bytes,1,opt,name=pre_reference,json=preReference,proto3" json:"pre_reference,omitempty"`
	// DSS subscribers that this client now has the obligation to notify of the Entity just deleted.  This client must call DELETE for each provided URL according to the `/entity_details` path API.
	Subscribers          []*SubscriberToNotify `protobuf:"bytes,2,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteUASReporterResponse) Reset()         { *m = DeleteUASReporterResponse{} }
func (m *DeleteUASReporterResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUASReporterResponse) ProtoMessage()    {}
func (*DeleteUASReporterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{1}
}

func (m *DeleteUASReporterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUASReporterResponse.Unmarshal(m, b)
}
func (m *DeleteUASReporterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUASReporterResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUASReporterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUASReporterResponse.Merge(m, src)
}
func (m *DeleteUASReporterResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUASReporterResponse.Size(m)
}
func (m *DeleteUASReporterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUASReporterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUASReporterResponse proto.InternalMessageInfo

func (m *DeleteUASReporterResponse) GetPreReference() *UASReporter {
	if m != nil {
		return m.PreReference
	}
	return nil
}

func (m *DeleteUASReporterResponse) GetSubscribers() []*SubscriberToNotify {
	if m != nil {
		return m.Subscribers
	}
	return nil
}

// Response for a successful request to delete an Subscription.
type DeleteSubscriptionResponse struct {
	// The Subscription which was deleted.
	Subscription         *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteSubscriptionResponse) Reset()         { *m = DeleteSubscriptionResponse{} }
func (m *DeleteSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionResponse) ProtoMessage()    {}
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{2}
}

func (m *DeleteSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionResponse.Unmarshal(m, b)
}
func (m *DeleteSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionResponse.Merge(m, src)
}
func (m *DeleteSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionResponse.Size(m)
}
func (m *DeleteSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionResponse proto.InternalMessageInfo

func (m *DeleteSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	// SubscriptionUUID of the subscription of interest.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionRequest) Reset()         { *m = DeleteSubscriptionRequest{} }
func (m *DeleteSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionRequest) ProtoMessage()    {}
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{3}
}

func (m *DeleteSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionRequest.Unmarshal(m, b)
}
func (m *DeleteSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionRequest.Merge(m, src)
}
func (m *DeleteSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionRequest.Size(m)
}
func (m *DeleteSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionRequest proto.InternalMessageInfo

func (m *DeleteSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// A declaration of an Entity.  The DSS reports only these EntityReferences and clients must obtain full details peer-to-peer from the creator/owner.
//
// `details_url` is required for all Entity types except `PositionReporting`.
type UASReporter struct {
	DetailsUrl string `protobuf:"bytes,1,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	// A url endpoint to poll for RID flight data.
	FlightsUrl string `protobuf:"bytes,2,opt,name=flights_url,json=flightsUrl,proto3" json:"flights_url,omitempty"`
	// Unique identifier for this object.  Created by client, and client must respond to a peer request for details about this Entity according to this ID.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner, and only requiring EntitySignatures for unowned Entities.
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// A planning client does not need to consider this Entity when considering time periods that will start after time_end.
	TimeEnd string `protobuf:"bytes,5,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// A planning client does not need to consider this Entity when considering time periods that will end before start_time.
	TimeStart string `protobuf:"bytes,6,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	// Extracted from the EntitySignature if specified, or assigned and incremented automatically otherwise.  When increased, indicates that an Entity has changed (allows another client client to optimize full Entity retrieval for only those Entities which have changed since client’s cache).
	Version int32 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	// The bounding spacetime extents of this Entity.  Start and end times must be specified.  Spatial information is translated into DAR cells internally by the DSS then discarded.
	Extents              *Volume4D `protobuf:"bytes,8,opt,name=extents,proto3" json:"extents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UASReporter) Reset()         { *m = UASReporter{} }
func (m *UASReporter) String() string { return proto.CompactTextString(m) }
func (*UASReporter) ProtoMessage()    {}
func (*UASReporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{4}
}

func (m *UASReporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UASReporter.Unmarshal(m, b)
}
func (m *UASReporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UASReporter.Marshal(b, m, deterministic)
}
func (m *UASReporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UASReporter.Merge(m, src)
}
func (m *UASReporter) XXX_Size() int {
	return xxx_messageInfo_UASReporter.Size(m)
}
func (m *UASReporter) XXX_DiscardUnknown() {
	xxx_messageInfo_UASReporter.DiscardUnknown(m)
}

var xxx_messageInfo_UASReporter proto.InternalMessageInfo

func (m *UASReporter) GetDetailsUrl() string {
	if m != nil {
		return m.DetailsUrl
	}
	return ""
}

func (m *UASReporter) GetFlightsUrl() string {
	if m != nil {
		return m.FlightsUrl
	}
	return ""
}

func (m *UASReporter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UASReporter) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *UASReporter) GetTimeEnd() string {
	if m != nil {
		return m.TimeEnd
	}
	return ""
}

func (m *UASReporter) GetTimeStart() string {
	if m != nil {
		return m.TimeStart
	}
	return ""
}

func (m *UASReporter) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UASReporter) GetExtents() *Volume4D {
	if m != nil {
		return m.Extents
	}
	return nil
}

// An enclosed area on the earth.
// The bounding edges of this polygon shall be the shortest paths between connected vertices.  This means, for instance, that the edge between two points both defined at a particular latitude is not generally contained at that latitude.
// The winding order shall be interpreted as the order which produces the smaller area.
// The path between two vertices shall be the shortest possible path between those vertices.
// Edges may not cross.
// Vertices may not be duplicated.  In particular, the final polygon vertex shall not be identical to the first vertex.
type GeoPolygon struct {
	Vertices             []*LatLngPoint `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GeoPolygon) Reset()         { *m = GeoPolygon{} }
func (m *GeoPolygon) String() string { return proto.CompactTextString(m) }
func (*GeoPolygon) ProtoMessage()    {}
func (*GeoPolygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{5}
}

func (m *GeoPolygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoPolygon.Unmarshal(m, b)
}
func (m *GeoPolygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoPolygon.Marshal(b, m, deterministic)
}
func (m *GeoPolygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoPolygon.Merge(m, src)
}
func (m *GeoPolygon) XXX_Size() int {
	return xxx_messageInfo_GeoPolygon.Size(m)
}
func (m *GeoPolygon) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoPolygon.DiscardUnknown(m)
}

var xxx_messageInfo_GeoPolygon proto.InternalMessageInfo

func (m *GeoPolygon) GetVertices() []*LatLngPoint {
	if m != nil {
		return m.Vertices
	}
	return nil
}

type SearchUASReportersRequest struct {
	// The area in which to search for Entities.  Some Entities near this area but wholly outside it may also be returned.
	Area string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	// If specified, indicates non-interest in any Entities that end before this time.
	EarliestTime string `protobuf:"bytes,2,opt,name=earliest_time,json=earliestTime,proto3" json:"earliest_time,omitempty"`
	// If specified, indicates non-interest in any Entities that start after this time.
	LatestTime string `protobuf:"bytes,3,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"`
	// If specified, indicates non-interest in Entities entirely above this altitude in meters above the WGS84 datum.
	MaxAltitude float64 `protobuf:"fixed64,4,opt,name=max_altitude,json=maxAltitude,proto3" json:"max_altitude,omitempty"`
	// If specified, indicates non-interest in Entities entirely below this altitude in meters above the WGS84 datum.
	MinAltitude          float64  `protobuf:"fixed64,5,opt,name=min_altitude,json=minAltitude,proto3" json:"min_altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUASReportersRequest) Reset()         { *m = SearchUASReportersRequest{} }
func (m *SearchUASReportersRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUASReportersRequest) ProtoMessage()    {}
func (*SearchUASReportersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{6}
}

func (m *SearchUASReportersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUASReportersRequest.Unmarshal(m, b)
}
func (m *SearchUASReportersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUASReportersRequest.Marshal(b, m, deterministic)
}
func (m *SearchUASReportersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUASReportersRequest.Merge(m, src)
}
func (m *SearchUASReportersRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUASReportersRequest.Size(m)
}
func (m *SearchUASReportersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUASReportersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUASReportersRequest proto.InternalMessageInfo

func (m *SearchUASReportersRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *SearchUASReportersRequest) GetEarliestTime() string {
	if m != nil {
		return m.EarliestTime
	}
	return ""
}

func (m *SearchUASReportersRequest) GetLatestTime() string {
	if m != nil {
		return m.LatestTime
	}
	return ""
}

func (m *SearchUASReportersRequest) GetMaxAltitude() float64 {
	if m != nil {
		return m.MaxAltitude
	}
	return 0
}

func (m *SearchUASReportersRequest) GetMinAltitude() float64 {
	if m != nil {
		return m.MinAltitude
	}
	return 0
}

// Response to DSS query for references to Entities in an area of interest.
type SearchUASReportersResponse struct {
	// Declarations/summaries/references of Entities in the area of interest.
	PreReferences        []*UASReporter `protobuf:"bytes,1,rep,name=pre_references,json=preReferences,proto3" json:"pre_references,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchUASReportersResponse) Reset()         { *m = SearchUASReportersResponse{} }
func (m *SearchUASReportersResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUASReportersResponse) ProtoMessage()    {}
func (*SearchUASReportersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{7}
}

func (m *SearchUASReportersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUASReportersResponse.Unmarshal(m, b)
}
func (m *SearchUASReportersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUASReportersResponse.Marshal(b, m, deterministic)
}
func (m *SearchUASReportersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUASReportersResponse.Merge(m, src)
}
func (m *SearchUASReportersResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUASReportersResponse.Size(m)
}
func (m *SearchUASReportersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUASReportersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUASReportersResponse proto.InternalMessageInfo

func (m *SearchUASReportersResponse) GetPreReferences() []*UASReporter {
	if m != nil {
		return m.PreReferences
	}
	return nil
}

type GetSubscriptionRequest struct {
	// SubscriptionUUID of the subscription of interest.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubscriptionRequest) Reset()         { *m = GetSubscriptionRequest{} }
func (m *GetSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionRequest) ProtoMessage()    {}
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{8}
}

func (m *GetSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionRequest.Unmarshal(m, b)
}
func (m *GetSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionRequest.Merge(m, src)
}
func (m *GetSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionRequest.Size(m)
}
func (m *GetSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionRequest proto.InternalMessageInfo

func (m *GetSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetSubscriptionResponse struct {
	Subscription         *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSubscriptionResponse) Reset()         { *m = GetSubscriptionResponse{} }
func (m *GetSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubscriptionResponse) ProtoMessage()    {}
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{9}
}

func (m *GetSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubscriptionResponse.Unmarshal(m, b)
}
func (m *GetSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *GetSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubscriptionResponse.Merge(m, src)
}
func (m *GetSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubscriptionResponse.Size(m)
}
func (m *GetSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubscriptionResponse proto.InternalMessageInfo

func (m *GetSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

type SearchSubscriptionsRequest struct {
	// The area in which to search for Subscriptions.  Some Subscriptions near this area but wholly outside it may also be returned.
	Area string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	// If specified, indicates non-interest in subscriptions for volumes entirely above this altitude in meters above the WGS84 datum.
	MaxAltitude float64 `protobuf:"fixed64,2,opt,name=max_altitude,json=maxAltitude,proto3" json:"max_altitude,omitempty"`
	// If specified, indicates non-interest in subscriptions for volumes entirely below this altitude in meters above the WGS84 datum.
	MinAltitude float64 `protobuf:"fixed64,3,opt,name=min_altitude,json=minAltitude,proto3" json:"min_altitude,omitempty"`
	// If specified, only return Subscriptions that are capable of producing notifications for the specified EntityTypes.
	TypesFilter          string   `protobuf:"bytes,4,opt,name=types_filter,json=typesFilter,proto3" json:"types_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSubscriptionsRequest) Reset()         { *m = SearchSubscriptionsRequest{} }
func (m *SearchSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSubscriptionsRequest) ProtoMessage()    {}
func (*SearchSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{10}
}

func (m *SearchSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSubscriptionsRequest.Unmarshal(m, b)
}
func (m *SearchSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *SearchSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSubscriptionsRequest.Merge(m, src)
}
func (m *SearchSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSubscriptionsRequest.Size(m)
}
func (m *SearchSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSubscriptionsRequest proto.InternalMessageInfo

func (m *SearchSubscriptionsRequest) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *SearchSubscriptionsRequest) GetMaxAltitude() float64 {
	if m != nil {
		return m.MaxAltitude
	}
	return 0
}

func (m *SearchSubscriptionsRequest) GetMinAltitude() float64 {
	if m != nil {
		return m.MinAltitude
	}
	return 0
}

func (m *SearchSubscriptionsRequest) GetTypesFilter() string {
	if m != nil {
		return m.TypesFilter
	}
	return ""
}

// Response to DSS query for subscriptions in a particular area.
type SearchSubscriptionsResponse struct {
	// Subscriptions that overlap the specified area.
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchSubscriptionsResponse) Reset()         { *m = SearchSubscriptionsResponse{} }
func (m *SearchSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchSubscriptionsResponse) ProtoMessage()    {}
func (*SearchSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{11}
}

func (m *SearchSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSubscriptionsResponse.Unmarshal(m, b)
}
func (m *SearchSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *SearchSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSubscriptionsResponse.Merge(m, src)
}
func (m *SearchSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchSubscriptionsResponse.Size(m)
}
func (m *SearchSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSubscriptionsResponse proto.InternalMessageInfo

func (m *SearchSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

// Point on the earth's surface.
type LatLngPoint struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLngPoint) Reset()         { *m = LatLngPoint{} }
func (m *LatLngPoint) String() string { return proto.CompactTextString(m) }
func (*LatLngPoint) ProtoMessage()    {}
func (*LatLngPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{12}
}

func (m *LatLngPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLngPoint.Unmarshal(m, b)
}
func (m *LatLngPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLngPoint.Marshal(b, m, deterministic)
}
func (m *LatLngPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLngPoint.Merge(m, src)
}
func (m *LatLngPoint) XXX_Size() int {
	return xxx_messageInfo_LatLngPoint.Size(m)
}
func (m *LatLngPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLngPoint.DiscardUnknown(m)
}

var xxx_messageInfo_LatLngPoint proto.InternalMessageInfo

func (m *LatLngPoint) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLngPoint) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

// Parameters for a request to create or update a reference to an Entity in the DSS.
type PutUASReporterRequest struct {
	DetailsUrl string `protobuf:"bytes,1,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	// A url endpoint to poll for RID flight data.
	FlightsUrl string `protobuf:"bytes,2,opt,name=flights_url,json=flightsUrl,proto3" json:"flights_url,omitempty"`
	// Unique identifier for this object.  Created by client, and client must respond to a peer request for details about this Entity according to this ID.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// A planning client does not need to consider this Entity when considering time periods that will start after time_end.
	TimeEnd string `protobuf:"bytes,4,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// A planning client does not need to consider this Entity when considering time periods that will end before start_time.
	TimeStart string `protobuf:"bytes,5,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	// The bounding spacetime extents of this Entity.  Start and end times must be specified.  Spatial information is translated into DAR cells internally by the DSS then discarded.
	Extents              *Volume4D `protobuf:"bytes,6,opt,name=extents,proto3" json:"extents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutUASReporterRequest) Reset()         { *m = PutUASReporterRequest{} }
func (m *PutUASReporterRequest) String() string { return proto.CompactTextString(m) }
func (*PutUASReporterRequest) ProtoMessage()    {}
func (*PutUASReporterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{13}
}

func (m *PutUASReporterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUASReporterRequest.Unmarshal(m, b)
}
func (m *PutUASReporterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUASReporterRequest.Marshal(b, m, deterministic)
}
func (m *PutUASReporterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUASReporterRequest.Merge(m, src)
}
func (m *PutUASReporterRequest) XXX_Size() int {
	return xxx_messageInfo_PutUASReporterRequest.Size(m)
}
func (m *PutUASReporterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUASReporterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUASReporterRequest proto.InternalMessageInfo

func (m *PutUASReporterRequest) GetDetailsUrl() string {
	if m != nil {
		return m.DetailsUrl
	}
	return ""
}

func (m *PutUASReporterRequest) GetFlightsUrl() string {
	if m != nil {
		return m.FlightsUrl
	}
	return ""
}

func (m *PutUASReporterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutUASReporterRequest) GetTimeEnd() string {
	if m != nil {
		return m.TimeEnd
	}
	return ""
}

func (m *PutUASReporterRequest) GetTimeStart() string {
	if m != nil {
		return m.TimeStart
	}
	return ""
}

func (m *PutUASReporterRequest) GetExtents() *Volume4D {
	if m != nil {
		return m.Extents
	}
	return nil
}

// Response to a request to create or update a reference to an Entity in the DSS.
type PutUASReporterResponse struct {
	// Resulting reference stored in DSS.
	PreReference *UASReporter `protobuf:"bytes,1,opt,name=pre_reference,json=preReference,proto3" json:"pre_reference,omitempty"`
	// DSS subscribers that this client now has the obligation to notify of the Entity changes just made.  This client must call PUT for each provided URL according to the `/entity_details` path API.
	Subscribers          []*SubscriberToNotify `protobuf:"bytes,2,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutUASReporterResponse) Reset()         { *m = PutUASReporterResponse{} }
func (m *PutUASReporterResponse) String() string { return proto.CompactTextString(m) }
func (*PutUASReporterResponse) ProtoMessage()    {}
func (*PutUASReporterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{14}
}

func (m *PutUASReporterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUASReporterResponse.Unmarshal(m, b)
}
func (m *PutUASReporterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUASReporterResponse.Marshal(b, m, deterministic)
}
func (m *PutUASReporterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUASReporterResponse.Merge(m, src)
}
func (m *PutUASReporterResponse) XXX_Size() int {
	return xxx_messageInfo_PutUASReporterResponse.Size(m)
}
func (m *PutUASReporterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUASReporterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutUASReporterResponse proto.InternalMessageInfo

func (m *PutUASReporterResponse) GetPreReference() *UASReporter {
	if m != nil {
		return m.PreReference
	}
	return nil
}

func (m *PutUASReporterResponse) GetSubscribers() []*SubscriberToNotify {
	if m != nil {
		return m.Subscribers
	}
	return nil
}

// Parameters for a request to create or update a subscription in the DSS.
type PutSubscriptionRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// This subscription will automatically be deleted after this time if it has not been refreshed by then.  If not specified when creating a subscription with a UTM scope, this subscription will be automatically deleted if it hasn't been used for a certain amount of time.  If not specified when creating a subscription without a UTM scope (such as for PositionReporting Entities), this value will be automatically set the maximum allowed Subscription duration in the future.
	Expiry string `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// The geographic extents of the volume to subscribe to.
	Extents *Volume3D `protobuf:"bytes,3,opt,name=extents,proto3" json:"extents,omitempty"`
	// Other clients will be instructed by the DSS to call this endpoint with created/updated Entity details when they create, update, or delete an Entity relevant to this Subscription.
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutSubscriptionRequest) Reset()         { *m = PutSubscriptionRequest{} }
func (m *PutSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*PutSubscriptionRequest) ProtoMessage()    {}
func (*PutSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{15}
}

func (m *PutSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSubscriptionRequest.Unmarshal(m, b)
}
func (m *PutSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *PutSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSubscriptionRequest.Merge(m, src)
}
func (m *PutSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_PutSubscriptionRequest.Size(m)
}
func (m *PutSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutSubscriptionRequest proto.InternalMessageInfo

func (m *PutSubscriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutSubscriptionRequest) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func (m *PutSubscriptionRequest) GetExtents() *Volume3D {
	if m != nil {
		return m.Extents
	}
	return nil
}

func (m *PutSubscriptionRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Response for a request to create or update a subscription.
type PutSubscriptionResponse struct {
	// Result of the operation on the subscription.
	Subscription *Subscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// Declarations/summaries/references of Entities in the subscription area at the time of creation/update.
	Entities             []*UASReporter `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutSubscriptionResponse) Reset()         { *m = PutSubscriptionResponse{} }
func (m *PutSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*PutSubscriptionResponse) ProtoMessage()    {}
func (*PutSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{16}
}

func (m *PutSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutSubscriptionResponse.Unmarshal(m, b)
}
func (m *PutSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *PutSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutSubscriptionResponse.Merge(m, src)
}
func (m *PutSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_PutSubscriptionResponse.Size(m)
}
func (m *PutSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutSubscriptionResponse proto.InternalMessageInfo

func (m *PutSubscriptionResponse) GetSubscription() *Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *PutSubscriptionResponse) GetEntities() []*UASReporter {
	if m != nil {
		return m.Entities
	}
	return nil
}

// Subscriber to notify of a change/mutation in the airspace.  This is provided by the DSS to a client changing the airspace, and it is the responsibility of the client changing the airspace (they will receive a set of SubscriberToNotifies) to send an AreaChangeNotification to each specified `callback`.
type SubscriberToNotify struct {
	// Subscription(s) prompting this notification.
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// The endpoint that the client mutating the airspace should provide the updated Entity to.
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscriberToNotify) Reset()         { *m = SubscriberToNotify{} }
func (m *SubscriberToNotify) String() string { return proto.CompactTextString(m) }
func (*SubscriberToNotify) ProtoMessage()    {}
func (*SubscriberToNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{17}
}

func (m *SubscriberToNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriberToNotify.Unmarshal(m, b)
}
func (m *SubscriberToNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriberToNotify.Marshal(b, m, deterministic)
}
func (m *SubscriberToNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriberToNotify.Merge(m, src)
}
func (m *SubscriberToNotify) XXX_Size() int {
	return xxx_messageInfo_SubscriberToNotify.Size(m)
}
func (m *SubscriberToNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriberToNotify.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriberToNotify proto.InternalMessageInfo

func (m *SubscriberToNotify) GetSubscriptionId() string {
	if m != nil {
		return m.SubscriptionId
	}
	return ""
}

func (m *SubscriberToNotify) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Specification of a geographic area that a client is interested in on an ongoing basis (e.g., “planning area”).  Internal to the DSS.
type Subscription struct {
	// If set, this subscription will be automatically removed after this time.
	Expires string `protobuf:"bytes,1,opt,name=expires,proto3" json:"expires,omitempty"`
	// Unique identifier for this subscription.
	Id                string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NotificationIndex int32  `protobuf:"varint,3,opt,name=notification_index,json=notificationIndex,proto3" json:"notification_index,omitempty"`
	// Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner.
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// Other clients must call this endpoint with created/updated Entity details when requested by the DSS (requested when they change the airspace in the associated cells).
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{18}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetNotificationIndex() int32 {
	if m != nil {
		return m.NotificationIndex
	}
	return 0
}

func (m *Subscription) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Subscription) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Altitude struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Reference            string   `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Altitude) Reset()         { *m = Altitude{} }
func (m *Altitude) String() string { return proto.CompactTextString(m) }
func (*Altitude) ProtoMessage()    {}
func (*Altitude) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{19}
}

func (m *Altitude) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Altitude.Unmarshal(m, b)
}
func (m *Altitude) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Altitude.Marshal(b, m, deterministic)
}
func (m *Altitude) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Altitude.Merge(m, src)
}
func (m *Altitude) XXX_Size() int {
	return xxx_messageInfo_Altitude.Size(m)
}
func (m *Altitude) XXX_DiscardUnknown() {
	xxx_messageInfo_Altitude.DiscardUnknown(m)
}

var xxx_messageInfo_Altitude proto.InternalMessageInfo

func (m *Altitude) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Altitude) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Altitude) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// A three-dimensional geographic volume consisting of a vertically-extruded polygon.
type Volume3D struct {
	// Maximum bounding altitude of this volume.
	AltitudeHi *Altitude `protobuf:"bytes,1,opt,name=altitude_hi,json=altitudeHi,proto3" json:"altitude_hi,omitempty"`
	// Minimum bounding altitude of this volume.
	AltitudeLo *Altitude `protobuf:"bytes,2,opt,name=altitude_lo,json=altitudeLo,proto3" json:"altitude_lo,omitempty"`
	// Projection of this volume onto the earth's surface.
	Footprint            *GeoPolygon `protobuf:"bytes,3,opt,name=footprint,proto3" json:"footprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Volume3D) Reset()         { *m = Volume3D{} }
func (m *Volume3D) String() string { return proto.CompactTextString(m) }
func (*Volume3D) ProtoMessage()    {}
func (*Volume3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{20}
}

func (m *Volume3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume3D.Unmarshal(m, b)
}
func (m *Volume3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume3D.Marshal(b, m, deterministic)
}
func (m *Volume3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume3D.Merge(m, src)
}
func (m *Volume3D) XXX_Size() int {
	return xxx_messageInfo_Volume3D.Size(m)
}
func (m *Volume3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume3D.DiscardUnknown(m)
}

var xxx_messageInfo_Volume3D proto.InternalMessageInfo

func (m *Volume3D) GetAltitudeHi() *Altitude {
	if m != nil {
		return m.AltitudeHi
	}
	return nil
}

func (m *Volume3D) GetAltitudeLo() *Altitude {
	if m != nil {
		return m.AltitudeLo
	}
	return nil
}

func (m *Volume3D) GetFootprint() *GeoPolygon {
	if m != nil {
		return m.Footprint
	}
	return nil
}

// Contiguous block of geographic spacetime.
type Volume4D struct {
	// Constant spatial extent of this volume.
	SpatialVolume *Volume3D `protobuf:"bytes,1,opt,name=spatial_volume,json=spatialVolume,proto3" json:"spatial_volume,omitempty"`
	// End time of this volume.
	TimeEnd string `protobuf:"bytes,2,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	// Beginning time of this volume.
	TimeStart            string   `protobuf:"bytes,3,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume4D) Reset()         { *m = Volume4D{} }
func (m *Volume4D) String() string { return proto.CompactTextString(m) }
func (*Volume4D) ProtoMessage()    {}
func (*Volume4D) Descriptor() ([]byte, []int) {
	return fileDescriptor_2659318a8590008d, []int{21}
}

func (m *Volume4D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume4D.Unmarshal(m, b)
}
func (m *Volume4D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume4D.Marshal(b, m, deterministic)
}
func (m *Volume4D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume4D.Merge(m, src)
}
func (m *Volume4D) XXX_Size() int {
	return xxx_messageInfo_Volume4D.Size(m)
}
func (m *Volume4D) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume4D.DiscardUnknown(m)
}

var xxx_messageInfo_Volume4D proto.InternalMessageInfo

func (m *Volume4D) GetSpatialVolume() *Volume3D {
	if m != nil {
		return m.SpatialVolume
	}
	return nil
}

func (m *Volume4D) GetTimeEnd() string {
	if m != nil {
		return m.TimeEnd
	}
	return ""
}

func (m *Volume4D) GetTimeStart() string {
	if m != nil {
		return m.TimeStart
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteUASReporterRequest)(nil), "dss.DeleteUASReporterRequest")
	proto.RegisterType((*DeleteUASReporterResponse)(nil), "dss.DeleteUASReporterResponse")
	proto.RegisterType((*DeleteSubscriptionResponse)(nil), "dss.DeleteSubscriptionResponse")
	proto.RegisterType((*DeleteSubscriptionRequest)(nil), "dss.DeleteSubscriptionRequest")
	proto.RegisterType((*UASReporter)(nil), "dss.UASReporter")
	proto.RegisterType((*GeoPolygon)(nil), "dss.GeoPolygon")
	proto.RegisterType((*SearchUASReportersRequest)(nil), "dss.SearchUASReportersRequest")
	proto.RegisterType((*SearchUASReportersResponse)(nil), "dss.SearchUASReportersResponse")
	proto.RegisterType((*GetSubscriptionRequest)(nil), "dss.GetSubscriptionRequest")
	proto.RegisterType((*GetSubscriptionResponse)(nil), "dss.GetSubscriptionResponse")
	proto.RegisterType((*SearchSubscriptionsRequest)(nil), "dss.SearchSubscriptionsRequest")
	proto.RegisterType((*SearchSubscriptionsResponse)(nil), "dss.SearchSubscriptionsResponse")
	proto.RegisterType((*LatLngPoint)(nil), "dss.LatLngPoint")
	proto.RegisterType((*PutUASReporterRequest)(nil), "dss.PutUASReporterRequest")
	proto.RegisterType((*PutUASReporterResponse)(nil), "dss.PutUASReporterResponse")
	proto.RegisterType((*PutSubscriptionRequest)(nil), "dss.PutSubscriptionRequest")
	proto.RegisterType((*PutSubscriptionResponse)(nil), "dss.PutSubscriptionResponse")
	proto.RegisterType((*SubscriberToNotify)(nil), "dss.SubscriberToNotify")
	proto.RegisterType((*Subscription)(nil), "dss.Subscription")
	proto.RegisterType((*Altitude)(nil), "dss.Altitude")
	proto.RegisterType((*Volume3D)(nil), "dss.Volume3D")
	proto.RegisterType((*Volume4D)(nil), "dss.Volume4D")
}

func init() { proto.RegisterFile("remote_id.proto", fileDescriptor_2659318a8590008d) }

var fileDescriptor_2659318a8590008d = []byte{
	// 1035 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xae, 0x93, 0xa6, 0x4d, 0x4f, 0xfe, 0x74, 0x3b, 0xbf, 0xfd, 0xb5, 0x69, 0xba, 0xcb, 0x16,
	0x73, 0xb1, 0x15, 0xb0, 0x95, 0xe8, 0x16, 0x21, 0xb8, 0x5b, 0xa9, 0xcb, 0xb2, 0xa2, 0x5a, 0x2a,
	0xa7, 0x5d, 0x24, 0xb8, 0xb0, 0xdc, 0xf8, 0xa4, 0x1d, 0xc9, 0xb1, 0xcd, 0xcc, 0x24, 0x24, 0x20,
	0xf1, 0x00, 0x48, 0x88, 0x6b, 0x9e, 0x85, 0x57, 0xe0, 0x25, 0x78, 0x05, 0x9e, 0x00, 0xcd, 0x1f,
	0x3b, 0xe3, 0xc4, 0x2e, 0x2b, 0x2d, 0x12, 0x77, 0x33, 0xdf, 0xf9, 0x66, 0xe6, 0x9c, 0x6f, 0xce,
	0x39, 0x63, 0xc3, 0x36, 0xc3, 0x71, 0x22, 0xd0, 0xa7, 0xe1, 0x71, 0xca, 0x12, 0x91, 0x90, 0x7a,
	0xc8, 0xb9, 0xfb, 0x3e, 0xf4, 0xce, 0x30, 0x42, 0x81, 0x57, 0xcf, 0x06, 0x1e, 0xa6, 0x09, 0x13,
	0xc8, 0x3c, 0xfc, 0x6e, 0x82, 0x5c, 0x90, 0x2e, 0xd4, 0x68, 0xd8, 0x73, 0x0e, 0x9d, 0xa3, 0x2d,
	0xaf, 0x46, 0x43, 0xf7, 0x17, 0x07, 0xf6, 0x4b, 0xc8, 0x3c, 0x4d, 0x62, 0x8e, 0xe4, 0x63, 0xe8,
	0xa4, 0x0c, 0x7d, 0x86, 0x23, 0x64, 0x18, 0x0f, 0x51, 0x2d, 0x6c, 0x9d, 0xdc, 0x3b, 0x0e, 0x39,
	0x3f, 0xb6, 0x17, 0xb4, 0x53, 0x86, 0x5e, 0xc6, 0x22, 0x9f, 0x42, 0x8b, 0x4f, 0xae, 0xf9, 0x90,
	0xd1, 0x6b, 0x64, 0xbc, 0x57, 0x3b, 0xac, 0x1f, 0xb5, 0x4e, 0xf6, 0xd4, 0xa2, 0x41, 0x8e, 0x5f,
	0x26, 0xaf, 0x12, 0x41, 0x47, 0x73, 0xcf, 0xe6, 0xba, 0x03, 0xe8, 0x6b, 0x77, 0x0c, 0x31, 0x15,
	0x34, 0x89, 0x2d, 0x7f, 0xda, 0xdc, 0xc2, 0x8d, 0x3b, 0x3b, 0xf6, 0xce, 0x7a, 0x41, 0x81, 0xe6,
	0x7e, 0x90, 0xc5, 0x58, 0xdc, 0xb4, 0x5c, 0x91, 0xbf, 0x1c, 0x68, 0x59, 0xa1, 0x91, 0x47, 0xd0,
	0x0a, 0x51, 0x04, 0x34, 0xe2, 0xfe, 0x84, 0x45, 0x86, 0x08, 0x06, 0xba, 0x62, 0x91, 0x24, 0x8c,
	0x22, 0x7a, 0x73, 0x2b, 0x34, 0xa1, 0xa6, 0x09, 0x06, 0x92, 0x04, 0x7d, 0x42, 0x3d, 0x3b, 0x81,
	0xdc, 0x87, 0x46, 0xf2, 0x7d, 0x8c, 0xac, 0xb7, 0xae, 0x20, 0x3d, 0x21, 0xfb, 0xd0, 0x14, 0x74,
	0x8c, 0x3e, 0xc6, 0x61, 0xaf, 0xa1, 0x0c, 0x9b, 0x72, 0xfe, 0x3c, 0x0e, 0xc9, 0x43, 0x00, 0x65,
	0xe2, 0x22, 0x60, 0xa2, 0xb7, 0xa1, 0x8c, 0x5b, 0x12, 0x19, 0x48, 0x80, 0xf4, 0x60, 0x73, 0x8a,
	0x8c, 0x4b, 0x41, 0x36, 0x0f, 0x9d, 0xa3, 0x86, 0x97, 0x4d, 0xc9, 0x63, 0xd8, 0xc4, 0x99, 0xc0,
	0x58, 0xf0, 0x5e, 0x53, 0x49, 0xd5, 0x51, 0x52, 0xbd, 0x4e, 0xa2, 0xc9, 0x18, 0x4f, 0xcf, 0xbc,
	0xcc, 0xea, 0x7e, 0x06, 0xf0, 0x02, 0x93, 0x8b, 0x24, 0x9a, 0xdf, 0x24, 0x31, 0xf9, 0x10, 0x9a,
	0x53, 0x64, 0x82, 0x0e, 0x91, 0xf7, 0x1c, 0x75, 0x79, 0xfa, 0xc6, 0xcf, 0x03, 0x71, 0x1e, 0xdf,
	0x5c, 0x24, 0x34, 0x16, 0x5e, 0xce, 0x70, 0x7f, 0x77, 0x60, 0x7f, 0x80, 0x01, 0x1b, 0xde, 0x5a,
	0xb2, 0xf1, 0x4c, 0x5e, 0x02, 0xeb, 0x01, 0xc3, 0xc0, 0xe8, 0xa6, 0xc6, 0xe4, 0x3d, 0xe8, 0x60,
	0xc0, 0x22, 0x8a, 0x5c, 0xf8, 0x32, 0x0c, 0xa3, 0x59, 0x3b, 0x03, 0x2f, 0xe9, 0x18, 0xa5, 0xac,
	0x51, 0x20, 0x72, 0x8a, 0x96, 0x0f, 0x34, 0xa4, 0x08, 0xef, 0x42, 0x7b, 0x1c, 0xcc, 0xfc, 0x20,
	0x12, 0x54, 0x4c, 0x42, 0x54, 0x6a, 0x3a, 0x5e, 0x6b, 0x1c, 0xcc, 0x9e, 0x19, 0x48, 0x51, 0x68,
	0xbc, 0xa0, 0x34, 0x0c, 0x85, 0xc6, 0x19, 0xc5, 0xbd, 0x82, 0x7e, 0x99, 0xf3, 0x26, 0xe1, 0x3e,
	0x81, 0x6e, 0xa1, 0x00, 0x8a, 0x7a, 0xd8, 0x15, 0xd0, 0xb1, 0x2b, 0x80, 0xbb, 0x47, 0xb0, 0xfb,
	0x02, 0xc5, 0x9b, 0xe4, 0xdb, 0x05, 0xec, 0xad, 0x30, 0xdf, 0x2e, 0xdd, 0x7f, 0x73, 0xb2, 0x98,
	0x6c, 0xd2, 0x9d, 0x37, 0xb2, 0xac, 0x65, 0xed, 0x9f, 0xb5, 0xac, 0xaf, 0x68, 0x29, 0x29, 0x62,
	0x9e, 0x22, 0xf7, 0x47, 0x34, 0x12, 0x79, 0x7e, 0xb7, 0x14, 0xf6, 0xb9, 0x82, 0xdc, 0xd7, 0x70,
	0x50, 0xea, 0x5a, 0xae, 0x77, 0xc7, 0x0e, 0x25, 0x93, 0xbb, 0x24, 0xe4, 0x22, 0xcf, 0xfd, 0x08,
	0x5a, 0x56, 0x76, 0x92, 0x7b, 0x50, 0x8f, 0x02, 0xa1, 0x42, 0x74, 0x3c, 0x39, 0x54, 0x48, 0x7c,
	0x63, 0x02, 0x93, 0x43, 0xf7, 0x0f, 0x07, 0xfe, 0x7f, 0x31, 0x11, 0x25, 0x4d, 0xf2, 0xdf, 0x2f,
	0x79, 0xbb, 0xb8, 0xd7, 0xef, 0x2a, 0xee, 0xc6, 0x72, 0x71, 0x5b, 0x25, 0xbc, 0x71, 0x67, 0x09,
	0xff, 0xec, 0xc0, 0xee, 0x72, 0x38, 0xff, 0x59, 0x1b, 0xff, 0x51, 0xf9, 0xf2, 0x06, 0xe9, 0x4f,
	0x76, 0x61, 0x03, 0x67, 0x29, 0x65, 0x73, 0xa3, 0xa2, 0x99, 0xd9, 0x71, 0xd7, 0x57, 0xe2, 0x7e,
	0xba, 0x88, 0x5b, 0x5e, 0xac, 0xbc, 0x03, 0xad, 0xaa, 0x1c, 0xba, 0x3f, 0xc1, 0xde, 0xca, 0xe1,
	0x6f, 0x55, 0x51, 0xb2, 0x21, 0x62, 0x2c, 0xa8, 0xa0, 0x98, 0xc9, 0xb0, 0xaa, 0x5d, 0xce, 0x70,
	0xbf, 0x02, 0xb2, 0xaa, 0x0f, 0x79, 0x0c, 0xdb, 0xf6, 0x9e, 0x7e, 0xae, 0x42, 0xd7, 0x86, 0x5f,
	0x86, 0x59, 0x40, 0xb5, 0x45, 0x40, 0xbf, 0x3a, 0xd0, 0xb6, 0xbd, 0x93, 0x1d, 0x5f, 0xc9, 0xa4,
	0xfa, 0x91, 0xca, 0x26, 0x33, 0x35, 0xf2, 0xd6, 0x72, 0x79, 0x9f, 0x00, 0x89, 0xe5, 0xf9, 0x74,
	0x18, 0xe8, 0x53, 0xe3, 0x10, 0x67, 0x4a, 0xd1, 0x86, 0xb7, 0x63, 0x5b, 0x5e, 0x4a, 0x43, 0xc5,
	0xd3, 0x64, 0x3c, 0x6a, 0x2c, 0x3c, 0xf2, 0xa0, 0x99, 0x57, 0xfd, 0x7d, 0x68, 0x4c, 0x83, 0x68,
	0xa2, 0xb3, 0xaa, 0xe6, 0xe9, 0x89, 0xec, 0x32, 0x93, 0x98, 0x0a, 0xe3, 0x8a, 0x1a, 0x93, 0x07,
	0xb0, 0xb5, 0xc8, 0x41, 0x5d, 0x1c, 0x0b, 0x40, 0xb6, 0xad, 0x66, 0x76, 0xbd, 0xe4, 0x18, 0x5a,
	0x59, 0xa7, 0xf1, 0x6f, 0xa9, 0xb9, 0x27, 0x9d, 0x02, 0xd9, 0xc1, 0x1e, 0x64, 0x8c, 0x2f, 0x68,
	0x81, 0x1f, 0x25, 0xea, 0xd4, 0x6a, 0xfe, 0x79, 0x42, 0x9e, 0xc0, 0xd6, 0x28, 0x49, 0x44, 0xca,
	0x68, 0x2c, 0x4c, 0x82, 0x6d, 0x2b, 0xf6, 0xe2, 0x19, 0xf4, 0x16, 0x0c, 0xf7, 0x87, 0xcc, 0xb5,
	0xd3, 0x33, 0x72, 0x0a, 0x5d, 0x9e, 0x06, 0x82, 0x06, 0x91, 0x3f, 0x55, 0x58, 0xc1, 0xbb, 0x3c,
	0x41, 0x3b, 0x86, 0xa4, 0x81, 0x42, 0x07, 0xa8, 0xdd, 0xd5, 0x01, 0xea, 0x4b, 0x1d, 0xe0, 0xe4,
	0xcf, 0x75, 0x80, 0xb3, 0xc1, 0x60, 0x80, 0x6c, 0x4a, 0x87, 0x48, 0x2e, 0x61, 0x67, 0xe5, 0x83,
	0x8d, 0x3c, 0x54, 0x67, 0x57, 0x7d, 0xf5, 0xf5, 0xdf, 0xa9, 0x32, 0xeb, 0xb2, 0x70, 0xd7, 0xc8,
	0xd7, 0x40, 0x56, 0x3f, 0x91, 0x88, 0xbd, 0xae, 0xa4, 0x98, 0xfb, 0x8f, 0x2a, 0xed, 0xf9, 0xc6,
	0xdf, 0xc2, 0xae, 0x6e, 0xf8, 0xcf, 0x65, 0x79, 0xcc, 0x17, 0x4f, 0xa4, 0xd9, 0xbc, 0xf2, 0xcb,
	0xc1, 0x6c, 0x5e, 0xfd, 0x38, 0xbb, 0x6b, 0xe4, 0x1b, 0xf8, 0x5f, 0xc9, 0x6b, 0x42, 0xec, 0x95,
	0x65, 0x4f, 0x60, 0xff, 0xb0, 0x9a, 0x90, 0xef, 0xfd, 0x0a, 0xb6, 0x97, 0xde, 0x65, 0x72, 0x60,
	0x32, 0xa4, 0xac, 0xb1, 0xf5, 0x1f, 0x94, 0x1b, 0xf3, 0xfd, 0xbe, 0x84, 0x6e, 0xb1, 0x3d, 0x93,
	0xbe, 0x5a, 0x51, 0xfa, 0x04, 0xf5, 0x0f, 0x4a, 0x6d, 0xb6, 0x73, 0x4b, 0x2d, 0x8e, 0xe4, 0x2b,
	0xaa, 0x9d, 0xab, 0xe8, 0x8a, 0xee, 0xda, 0xf5, 0x86, 0xfa, 0x7d, 0x78, 0xfa, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xce, 0xed, 0xe0, 0x13, 0x51, 0x0c, 0x00, 0x00,
}
