'To render with PlantUML:
'  java -jar plantuml.jar -o generated pool_new_1.puml
@startuml
participant "USS 1" as USS1

participant "Pool state" as PoolState

note over USS1: Initialize CA with dss-certs.sh

note over USS1: Use helm to deploy\nDSS instance

note over PoolState: Pool ready with\n1 instance


note over USS1: Run prober on DSS instance\nto verify functionality

note over PoolState: Pool verified with\n1 instance

@enduml
