'To render with PlantUML:
'  java -jar plantuml.jar -o generated subscriptions.puml
@startuml
participant "Entity\nconsumer" as EC
participant "Discovery and\nSynchronization Service" as DSS
participant "Entity producer\n(USS 1)" as EP1
participant "Entity producer\n(USS 2)" as EP2

EP1 -> DSS : PUT /dss/<entities>
note right: USS 1 creates\nnew Entity
activate DSS
DSS -->> EP1 : Success, no subscribers
deactivate

EC -> DSS : PUT /dss/subscriptions
note left: Consumer indicates\ninterest in area
activate DSS
DSS -->> EC : Existing Entity for USS 1
deactivate
note left: Consumer discovers\npre-existing Entity

EC -> EP1 : GET /uss/<entities>
activate EP1
EP1 -->> EC : Entity details
deactivate

note left: Consumer retrieves Entity\ndetails from USS 1
EP2 -> DSS : PUT /dss/<entities>
activate DSS
note right: USS 2 creates\nnew Entity
DSS -->> EP2 : Success, notify subscriber
deactivate

note right: DSS instructs USS 2 to notify\nconsumer of new Entity because\nof consumer's Subscription in the\nDSS
EP2 -> EC : POST /uss/<entities> with Entity details
activate EC
note left: Consumer receives Entity\ndetails via push from USS 2
EC -->> EP2 : Acknowledged
deactivate

@enduml
