{
 "title": "Cockroach Storage",
 "tags": [ "cockroach" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": "sys_uptime{app=\"cockroachdb\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{app=\"cockroachdb\",cluster=\"$cluster\"},pod_name)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Capacity: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)) - sum(sum(capacity_available{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Capacity Used: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) - sum(capacity_available{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)) / sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(capacity_available{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) / sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "1 - sum(capacity_available{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) / sum(capacity{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Live Bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(livebytes{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Raft log commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_logcommit_latency:rate1m:quantile_99{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "avg(rocksdb_read_amplification{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Raft command commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_commandcommit_latency:rate1m:quantile_99{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "File descriptor usage: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(sys_fd_open{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name) / sum(sys_fd_softlimit{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Raft Engine Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(raft_rocksdb_read_amplification{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Raft Engine Read Amplification"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rocksdb_num_sstables{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "Raft RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raft_rocksdb_num_sstables{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"} / (rocksdb_block_cache_hits{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"} + rocksdb_block_cache_misses{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"})",
     "legendFormat": "{{pod_name}}:{{store}}"
    }
   ]
  },
  {
   "title": "Raft RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "raft_rocksdb_block_cache_hits{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"} / (raft_rocksdb_block_cache_hits{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"} + raft_rocksdb_block_cache_misses{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"})",
     "legendFormat": "{{pod_name}}:{{store}}"
    }
   ]
  },
  {
   "title": "File Descriptors: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{app=\"cockroachdb\",cluster=\"$cluster\",pod_name=~\"$node\"}) by (pod_name))",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}