name: Continuous integration
on:
  pull_request: # All
  push:
    branches:
    - master
jobs:
  hygiene-tests:
    name: Repository hygiene
    runs-on: ubuntu-latest
    steps:
    - name: Job information
      run: |
        echo "Job information"
        echo "Trigger: ${{ github.event_name }}"
        echo "Host: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        docker images
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Python lint
      run: make python-lint
    - name: Automated hygiene verification
      run: make hygiene
    - name: Shell lint
      run: make shell-lint
    - name: Go lint
      run: make go-lint
    - name: Terraform lint
      run: make terraform-lint

  dss-tests:
    name: DSS tests
    runs-on: ubuntu-latest
    steps:
    - name: Job information
      run: |
        echo "Job information"
        echo "Trigger: ${{ github.event_name }}"
        echo "Host: ${{ runner.os }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        docker images
        go env
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Deployment infrastructure tests
      run: make evaluate-tanka
    - name: Go unit tests
      run: make test-go-units
    - name: Go unit tests with CockroachDB
      run: make test-go-units-crdb
    - name: Build dss image
      run: make build-dss
    - name: Tear down any pre-existing local DSS instance
      run: make down-locally
    - name: Start local DSS instance
      run: make start-locally
    - name: Probe local DSS instance
      run: make probe-locally
    - name: Bring down local DSS instance
      run: make down-locally
    - name: Checkout monitoring repository
      uses: actions/checkout@v2
      with:
        repository: interuss/monitoring
        submodules: true
        path: monitoring-repo
        ref: main  # consider checking out a tag instead? Downside is that we'd need to update it with each release
    - name: Run qualifier in monitoring repository
      run: |
        set -e
        cd monitoring-repo
        # Set the docker-compose file to use the locally built DSS instance
        # Note that on OS X you'll need to use `sed -i ''` instead of `sed -i`
        sed -i 's|interuss/dss:[^ ]*|interuss-local/dss:latest|g' build/dev/docker-compose.yaml
        # Start all required containers to run the qualifier
        make restart-all
        cd monitoring/uss_qualifier/
        # Run the qualifier
        ./run_locally.sh configurations.dev.noop,configurations.dev.uspace,configurations.dev.geoawareness_cis,configurations.dev.generate_rid_test_data,configurations.dev.geospatial_comprehension,configurations.dev.general_flight_auth,configurations.dev.message_signing,configurations.dev.dss_probing,configurations.dev.f3548_self_contained,configurations.dev.netrid_v22a,configurations.dev.netrid_v19
